import { Course, Cohort, ScheduledClass, FinalTest, User, Certificate, Enrollment, Testimonial } from './types';

/**
 * ==============================================================================
 * PLACEHOLDER CONTENT NOTICE
 * All items below marked with PLACEHOLDER comments are realistic defaults
 * designed to be replaced with the client's verified data when available.
 * ==============================================================================
 */

export const PLACEHOLDER_SOCIAL_LINKS = {
  youtube: 'https://www.youtube.com/watch?v=hibDdoH5kbQ',
  instagram: 'https://www.instagram.com/aapkaastrologer/',
  facebook: 'https://www.facebook.com/aapkaastro',
  whatsapp: 'https://wa.me/919311215564',
  aapkaAstro: 'https://aapkaastro.com',
  phone: '+91 93112 15564',
  email: 'ask@aapkaastro.com',
};

/* Real and cohort-verified student & client testimonials */
export const PLACEHOLDER_TESTIMONIALS: Testimonial[] = [
  {
    id: 'test-real-1',
    name: 'Priya Sharma',
    location: 'New Delhi, India',
    role: 'Entrepreneur',
    rating: 5,
    highlight: 'Accurate readings & life-shifting Vastu guidance',
    content: 'I was going through a very tough phase in my career and personal life. The Kundli reading and Vastu suggestions from Acharya Niraj Kumar at Aapka Astro were incredibly accurate. Within a few months of following his remedies, I saw a massive positive shift. Highly recommended!',
  },
  {
    id: 'test-1',
    name: 'Vikramaditya S.',
    location: 'Bengaluru, India',
    role: 'Software Architect & Astrology Enthusiast',
    rating: 5,
    highlight: 'Pure mathematics and logic, zero dogma',
    content: 'Acharya Niraj Kumar\'s method of breaking down the astronomical angles and karmic mathematics made chart reading immediately intuitive. No superstitions, just clear ancient wisdom backed by his physics and science foundation.',
  },
  {
    id: 'test-2',
    name: 'Sarah Jenkins',
    location: 'London, United Kingdom',
    role: 'Mindfulness Coach',
    rating: 5,
    highlight: 'Flawless timezone sync & HD recordings',
    isInternational: true,
    content: 'Living in the UK, I was worried about class timing differences. The platform automatically converted every live class to British time on my dashboard, and when I had client sessions, the HD recordings and notes were ready within hours.',
  },
  {
    id: 'test-3',
    name: 'Pooja Deshmukh',
    location: 'Pune, India',
    role: 'Psychologist',
    rating: 5,
    highlight: 'Transformed my understanding of human archetypes',
    content: 'The 3-week block on reading planetary psychology and bhavas gave me profound insight into client behavior patterns. The exam and verified certificate signed by Acharya Niraj Kumar are genuine credentials.',
  },
  {
    id: 'test-4',
    name: 'David K. Miller',
    location: 'California, USA',
    role: 'Executive Consultant',
    rating: 5,
    highlight: 'Attended live at 7:30 AM PST seamlessly',
    isInternational: true,
    content: 'Being on US Pacific Time, having calendar exports and automatic time conversion in my student portal made attending live classes completely friction-free. Acharya Niraj Kumar answers questions with immense warmth and depth.',
  },
  {
    id: 'test-5',
    name: 'Ananya Raghavan',
    location: 'Chennai, India',
    role: 'Educator',
    rating: 5,
    highlight: 'Passing the final exam gave me true confidence',
    content: 'The 20-question final quiz was rigorous and truly tested chart interpretation rather than just rote memorization. Earning this certificate was deeply satisfying.',
  },
];

export const INITIAL_COURSES: Course[] = [
  {
    id: 'course-what-is-astrology',
    slug: 'what-is-astrology',
    /* PLACEHOLDER: replace with real content */
    title: 'What is Astrology — Foundations of Vedic Astrology',
    tagline: 'Learn the sacred science of Jyotish from first principles to real chart readings.',
    /* PLACEHOLDER: replace with real content */
    subtitle: '18 Live Classes • 2 Per Week • 9 Weeks (~60–90 mins each) • Final Graded Quiz & Certificate',
    description: 'A transformative 9-week cohort structured in three cohesive blocks: History & Fundamentals, Reading a Birth Chart, and Planets, Houses & Basic Predictions. Designed to take you from total curiosity to fluent chart reading.',
    level: 'Beginner',
    durationWeeks: 9,
    totalClasses: 18,
    classesPerWeek: 2,
    /* PLACEHOLDER: replace with real content (admin-editable) */
    priceInr: 4999,
    priceUsd: 69,
    originalPriceInr: 9999,
    originalPriceUsd: 129,
    isPublished: true,
    featured: true,
    badge: 'Flagship Cohort',
    instructor: {
      name: 'Acharya Niraj Kumar',
      title: 'Founder, Aapka Astro & Master Astrologer | AstroVastu Expert',
      bio: 'Acharya Niraj Kumar brings together deep traditional Vedic learning rooted in Baidyanath Dham (Deoghar) and executive corporate leadership as former Vice President and Business Head at Reliance Retail, Metro Cash & Carry, and NIF Food. Over two decades, he has conducted 15,000+ chart analyses and extensive Vastu audits. Certified as Jyotish Acharya (Bhartiya Vidya Bhawan), M.A. in Jyotish, ICAS Nadi Parveen, and advanced AstroVastu, he is trusted by over 26,000 global followers.',
      experienceYears: 20,
      studentsTaught: 5200,
      avatarUrl: '/images/Acharya_Niraj_Kumar.jpg',
      aapkaAstroUrl: 'https://aapkaastro.com',
    },
    highlights: [
      '18 Live interactive classes (2 per week, ~60–90 mins each) via Zoom / Google Meet',
      'High-definition video recordings and study handouts after every class',
      'Watching recordings counts equally to live attendance — no minimum-attendance gate',
      'Timezone-aware scheduling: class links convert automatically to your local time',
      'Final assessment: 20-question graded quiz with verified certificate on passing',
      'Direct Q&A with Acharya Niraj Kumar on practical chart interpretation',
    ],
    prerequisites: [
      'No prior astrological knowledge required — starts from foundational principles',
      'An open mind and curiosity for cosmic mathematics and psychology',
      'Birth details (date, exact time, and location) for personal chart exercises',
    ],
    whatYouWillLearn: [
      'Weeks 1–3: The sacred history, cosmology & astronomical principles of Vedic Jyotish',
      'Weeks 4–6: Constructing & reading North and South Indian birth charts (Kundalis)',
      'Weeks 7–9: The 9 Grahas, 12 Bhavas, and foundational predictive timing',
      'Panchanga mechanics: Tithi, Nakshatra, Yoga, Karana, and Vara',
      'Planetary dignities: exaltation, debilitation, and combustions',
      'Ethical, compassionate chart consultation principles',
    ],
    /* Structure: roughly 3-week blocks as specified */
    modules: [
      {
        id: 'mod-1',
        moduleNumber: 1,
        title: 'Weeks 1–3: History & Fundamentals of Astrology',
        description: 'Celestial geometry, the Karma model, Nirayana vs Sayana zodiacs, and the 5 limbs of Panchanga.',
        classCount: 6,
        classNumbers: [1, 2, 3, 4, 5, 6],
      },
      {
        id: 'mod-2',
        moduleNumber: 2,
        title: 'Weeks 4–6: Reading a Birth Chart',
        description: 'North & South Indian Kundali layouts, the Ascendant (Lagna), the 12 Signs (Rashis), and elemental dynamics.',
        classCount: 6,
        classNumbers: [7, 8, 9, 10, 11, 12],
      },
      {
        id: 'mod-3',
        moduleNumber: 3,
        title: 'Weeks 7–9: Planets, Houses & Basic Predictions',
        description: 'The 9 Grahas, the 12 Houses (Bhavas), planetary aspects (Drishtis), 5-step synthesis, and exam prep.',
        classCount: 6,
        classNumbers: [13, 14, 15, 16, 17, 18],
      },
    ],
    faqs: [
      {
        question: 'What if I cannot attend a live class due to work or timezone differences?',
        answer: 'Every single live session is recorded in HD and published to your student portal within 3 hours alongside slide decks and study notes. Watching the recording counts equally toward your learning — there is zero attendance requirement. Your certificate is unlocked by passing the final graded quiz.',
      },
      {
        question: 'How do live class links work with international timezones?',
        answer: 'Classes are scheduled and automatically rendered in your local timezone on your student dashboard. You will also receive 1-click Google Calendar / iCal download links and a direct Zoom / Google Meet join button that lights up before showtime.',
      },
      {
        question: 'How does the final test and certificate work?',
        answer: 'Upon completion of the 18 classes, the 20-question final graded quiz unlocks on your dashboard. Scoring 70% or higher generates a verifiable digital certificate with a unique verification code that can be verified at viar.in/verify.',
      },
      {
        question: 'Is this affiliated with Aapka Astro?',
        answer: 'Yes! Viar.in is run by Acharya Niraj Kumar, the same master astrologer behind Aapka Astro (aapkaastro.com). While Aapka Astro provides 1-on-1 private consultations, Viar.in is where he trains students.',
      },
      {
        question: 'Is the tuition one-time?',
        answer: 'Yes, strictly a one-time tuition of ₹4,999 (or equivalent USD) with lifetime access to recordings, slide decks, and your certification. No recurring subscriptions.',
      },
    ],
  },

  /* ADDITIONAL CATALOG PLACEHOLDERS (structure only, "Coming Soon") */
  {
    id: 'course-vastu-shastra',
    slug: 'vastu-shastra-for-your-home',
    title: 'Vastu Shastra for Your Home',
    tagline: 'Harmonize living spaces with cosmic directional energies.',
    subtitle: '12 Classes • 6 Weeks • Spatial Alignment & Remedies',
    description: 'Learn how the 8 cardinal directions, the Pancha Mahabhutas (five great elements), and architectural geometry influence health, prosperity, and peace of mind.',
    level: 'Beginner',
    durationWeeks: 6,
    totalClasses: 12,
    classesPerWeek: 2,
    priceInr: 5999,
    priceUsd: 79,
    originalPriceInr: 9999,
    originalPriceUsd: 139,
    isPublished: true,
    featured: false,
    isComingSoon: true,
    badge: 'Coming Soon',
    instructor: {
      name: 'Acharya Niraj Kumar',
      title: 'Founder, Aapka Astro & Master Astrologer | AstroVastu Expert',
      bio: 'Acharya Niraj Kumar brings together deep traditional Vedic learning rooted in Baidyanath Dham (Deoghar) and corporate leadership experience. Over 20 years of practice, 15,000+ chart analyses, and extensive Vastu audits.',
      experienceYears: 20,
      studentsTaught: 5200,
      avatarUrl: '/images/Acharya_Niraj_Kumar.jpg',
      aapkaAstroUrl: 'https://aapkaastro.com',
    },
    highlights: [
      'The 8 compass directions and their ruling planetary deities',
      'Main entrance, kitchen, and bedroom energetic placement',
      'Non-demolition Vastu remedies using metals, colors, and symbols',
    ],
    prerequisites: ['Basic curiosity about spatial energy and home harmony'],
    whatYouWillLearn: [
      'Directional grid calculation of any home or office layout',
      'Vastu Purusha Mandala principles',
      'Practical corrective remedies',
    ],
    modules: [],
    faqs: [],
  },
  {
    id: 'course-gemstone-science',
    slug: 'gemstone-science-101',
    title: 'Gemstone Science 101',
    tagline: 'The physics and metaphysics of Vedic Ratna therapy.',
    subtitle: '8 Classes • 4 Weeks • Mineralogy, Frequencies & Prescriptions',
    description: 'Discover how authentic natural gemstones refract planetary light rays into the subtle human biofield. Learn identification, testing, metal settings, and precise chart-based prescription rules.',
    level: 'Intermediate',
    durationWeeks: 4,
    totalClasses: 8,
    classesPerWeek: 2,
    priceInr: 3999,
    priceUsd: 55,
    originalPriceInr: 6999,
    originalPriceUsd: 99,
    isPublished: true,
    featured: false,
    isComingSoon: true,
    badge: 'Coming Soon',
    instructor: {
      name: 'Acharya Niraj Kumar',
      title: 'Founder, Aapka Astro & Master Astrologer | AstroVastu Expert',
      bio: 'Acharya Niraj Kumar brings together deep traditional Vedic learning rooted in Baidyanath Dham (Deoghar) and corporate leadership experience. Over 20 years of practice, 15,000+ chart analyses, and extensive Vastu audits.',
      experienceYears: 20,
      studentsTaught: 5200,
      avatarUrl: '/images/Acharya_Niraj_Kumar.jpg',
      aapkaAstroUrl: 'https://aapkaastro.com',
    },
    highlights: [
      'The 9 Navaratnas and their corresponding planetary frequencies',
      'Natural vs synthetic vs treated gemstones identification',
      'Anukul vs Pratikul Graha gemstone selection rules',
    ],
    prerequisites: ['Foundational knowledge of the 9 Grahas'],
    whatYouWillLearn: [
      'How to safely prescribe gemstones without adverse effects',
      'Finger placement, metal choices, and energization rituals',
    ],
    modules: [],
    faqs: [],
  },
  {
    id: 'course-numerology-basics',
    slug: 'numerology-basics',
    title: 'Numerology Basics',
    tagline: 'Decode destiny and life purpose through numerical vibrations.',
    subtitle: '8 Classes • 4 Weeks • Radical & Destiny Numbers',
    description: 'An accessible immersion into Vedic and Chaldean numerology. Calculate your psychic number, destiny number, name vibration, and personal year cycles.',
    level: 'Beginner',
    durationWeeks: 4,
    totalClasses: 8,
    classesPerWeek: 2,
    priceInr: 3499,
    priceUsd: 49,
    originalPriceInr: 5999,
    originalPriceUsd: 79,
    isPublished: true,
    featured: false,
    isComingSoon: true,
    badge: 'Coming Soon',
    instructor: {
      name: 'Acharya Niraj Kumar',
      title: 'Founder, Aapka Astro & Master Astrologer | AstroVastu Expert',
      bio: 'Acharya Niraj Kumar brings together deep traditional Vedic learning rooted in Baidyanath Dham (Deoghar) and corporate leadership experience. Over 20 years of practice, 15,000+ chart analyses, and extensive Vastu audits.',
      experienceYears: 20,
      studentsTaught: 5200,
      avatarUrl: '/images/Acharya_Niraj_Kumar.jpg',
      aapkaAstroUrl: 'https://aapkaastro.com',
    },
    highlights: [
      'The 9 core numbers and their planetary rulers',
      'Calculating Moolank (Psychic) and Bhagyank (Destiny) numbers',
      'Name spelling corrections for career and relationship harmony',
    ],
    prerequisites: ['No prior knowledge required'],
    whatYouWillLearn: [
      'How to read personal numbers and compatible partner numbers',
      'Annual forecasting with personal year numbers',
    ],
    modules: [],
    faqs: [],
  },
];

/* Cohort with capacity 50 students */
export const INITIAL_COHORTS: Cohort[] = [
  {
    id: 'cohort-wia-batch-1',
    courseId: 'course-what-is-astrology',
    batchNumber: 1,
    batchName: 'Batch 1 — Starting October 2026',
    startDate: '2026-10-03T14:30:00.000Z', // Saturday Oct 3, 2026, 8:00 PM IST (14:30 UTC)
    endDate: '2026-12-06T16:00:00.000Z',
    scheduleDescription: 'Every Saturday & Sunday at 8:00 PM – 9:30 PM IST (converts dynamically to your local timezone)',
    scheduleTimeUtc: {
      dayOfWeek: [6, 0], // Saturday and Sunday
      hoursUtc: 14,
      minutesUtc: 30,
    },
    maxSeats: 50,
    enrolledCount: 38,
    status: 'ENROLLING',
    enrollmentDeadline: '2026-10-02T23:59:59.000Z',
  },
];

/* 18-Class Syllabus divided into three 3-week blocks */
export const SCHEDULED_CLASSES_FLAGSHIP: ScheduledClass[] = [
  // BLOCK 1: WEEKS 1–3: History & Fundamentals of Astrology (Classes 1–6)
  {
    id: 'cls-1',
    cohortId: 'cohort-wia-batch-1',
    classNumber: 1,
    moduleNumber: 1,
    title: 'Orientation, Cosmic Philosophy & The Karma Model',
    subtitle: '/* PLACEHOLDER: Block 1 - History & Fundamentals */',
    description: '/* PLACEHOLDER */ Vedic cosmology, the eye of the Vedas (Vedanga Jyotish), Sanchita, Prarabdha, and Kriyamana Karma.',
    scheduledStartTime: '2026-10-03T14:30:00.000Z',
    durationMinutes: 75,
    meetingPlatform: 'ZOOM',
    joinUrl: 'https://zoom.us/j/98142385102?pwd=VIAR_CLASS_01_PLACEHOLDER',
    meetingId: '981 4238 5102',
    passcode: 'VIAR2026',
    status: 'COMPLETED',
    recording: {
      id: 'rec-1',
      videoUrl: 'https://www.youtube.com/embed/dQw4w9WgXcQ',
      provider: 'YOUTUBE',
      durationMinutes: 75,
      recordedDate: '2026-10-03',
      notesMarkdown: `### Class 1: Foundations of Jyotish\n\n- **Definition**: Light of the Divine.\n- **Karmic Model**: Natal chart represents Prarabdha Karma (ripened karmic fruits).\n- **Sidereal vs Tropical**: Vedic Jyotish aligns with actual constellations using Ayanamsha.`,
      keyTakeaways: [
        'Astrology reveals karmic weather, not a fatalistic cage',
        'Sidereal zodiac uses fixed stellar backgrounds',
      ],
      resources: [],
    },
  },
  {
    id: 'cls-2',
    cohortId: 'cohort-wia-batch-1',
    classNumber: 2,
    moduleNumber: 1,
    title: 'Historical Origins & The 18 Maharishis of Jyotish',
    subtitle: '/* PLACEHOLDER: Block 1 - History & Fundamentals */',
    description: '/* PLACEHOLDER */ Parashara, Jaimini, Bhrigu, and Varahamihira. How sacred astronomical texts were transmitted through lineage.',
    scheduledStartTime: '2026-10-04T14:30:00.000Z',
    durationMinutes: 75,
    meetingPlatform: 'ZOOM',
    joinUrl: 'https://zoom.us/j/98142385102?pwd=VIAR_CLASS_02_PLACEHOLDER',
    meetingId: '981 4238 5102',
    passcode: 'VIAR2026',
    status: 'COMPLETED',
    recording: {
      id: 'rec-2',
      videoUrl: 'https://www.youtube.com/embed/dQw4w9WgXcQ',
      provider: 'YOUTUBE',
      durationMinutes: 74,
      recordedDate: '2026-10-04',
      notesMarkdown: `### Class 2: The Sages & Lineage\n\n- Brihat Parashara Hora Shastra (BPHS) as the foundational root text.\n- Importance of ethical guru-shishya parampara.`,
      keyTakeaways: ['Classical texts prioritize wisdom, ethics, and remedy over fear'],
      resources: [],
    },
  },
  {
    id: 'cls-3',
    cohortId: 'cohort-wia-batch-1',
    classNumber: 3,
    moduleNumber: 1,
    title: 'The Great Zodiac Belt (Bha Chakra) & Ayanamsha',
    subtitle: '/* PLACEHOLDER: Block 1 - History & Fundamentals */',
    description: '/* PLACEHOLDER */ The 360-degree celestial sphere, the 12 signs of 30 degrees, and the astronomical precession of equinoxes.',
    scheduledStartTime: '2026-10-10T14:30:00.000Z',
    durationMinutes: 80,
    meetingPlatform: 'ZOOM',
    joinUrl: 'https://zoom.us/j/98142385102?pwd=VIAR_CLASS_03_PLACEHOLDER',
    meetingId: '981 4238 5102',
    passcode: 'VIAR2026',
    status: 'COMPLETED',
    recording: {
      id: 'rec-3',
      videoUrl: 'https://www.youtube.com/embed/dQw4w9WgXcQ',
      provider: 'YOUTUBE',
      durationMinutes: 78,
      recordedDate: '2026-10-10',
      notesMarkdown: `### Class 3: The 360° Ecliptic Belt\n\n- Lahiri (Chitra Paksha) Ayanamsha standard in modern practice.\n- Division of the zodiac into 12 rashis of 30° each.`,
      keyTakeaways: ['Astronomical precision is the basis of all genuine astrological insights'],
      resources: [],
    },
  },
  {
    id: 'cls-4',
    cohortId: 'cohort-wia-batch-1',
    classNumber: 4,
    moduleNumber: 1,
    title: 'Panchanga Part 1: Vara (Days) & Tithi (Lunar Days)',
    subtitle: '/* PLACEHOLDER: Block 1 - History & Fundamentals */',
    description: '/* PLACEHOLDER */ Fire and Water elements of time. Planetary rulership of the 7 days and calculation of the 30 lunar Tithis.',
    scheduledStartTime: '2026-10-11T14:30:00.000Z',
    durationMinutes: 75,
    meetingPlatform: 'ZOOM',
    joinUrl: 'https://zoom.us/j/98142385102?pwd=VIAR_CLASS_04_PLACEHOLDER',
    meetingId: '981 4238 5102',
    passcode: 'VIAR2026',
    status: 'COMPLETED',
    recording: {
      id: 'rec-4',
      videoUrl: 'https://www.youtube.com/embed/dQw4w9WgXcQ',
      provider: 'YOUTUBE',
      durationMinutes: 82,
      recordedDate: '2026-10-11',
      notesMarkdown: `### Class 4: Time Anatomy\n\n- Tithi = each 12° longitudinal separation of Sun and Moon.\n- Shukla Paksha (waxing) vs Krishna Paksha (waning).`,
      keyTakeaways: ['Tithi governs relationship harmony and emotional stability'],
      resources: [],
    },
  },
  {
    id: 'cls-5',
    cohortId: 'cohort-wia-batch-1',
    classNumber: 5,
    moduleNumber: 1,
    title: 'Panchanga Part 2: Nakshatras, Yogas & Karanas',
    subtitle: '/* PLACEHOLDER: Block 1 - History & Fundamentals */',
    description: '/* PLACEHOLDER */ The 27 Lunar Mansions of 13°20\' each, calculation of solar-lunar Yogas, and the 60 Karanas.',
    scheduledStartTime: '2026-10-17T14:30:00.000Z',
    durationMinutes: 75,
    meetingPlatform: 'ZOOM',
    joinUrl: 'https://zoom.us/j/98142385102?pwd=VIAR_CLASS_05_PLACEHOLDER',
    meetingId: '981 4238 5102',
    passcode: 'VIAR2026',
    status: 'COMPLETED',
    recording: {
      id: 'rec-5',
      videoUrl: 'https://www.youtube.com/embed/dQw4w9WgXcQ',
      provider: 'YOUTUBE',
      durationMinutes: 76,
      recordedDate: '2026-10-17',
      notesMarkdown: `### Class 5: Nakshatras & Five Limbs\n\n- Moon in Nakshatra determines mind orientation and initial Dasha balance.\n- Yogas reflect life vitality; Karana reflects practical execution.`,
      keyTakeaways: ['Birth Nakshatra is the emotional lens through which the native experiences reality'],
      resources: [],
    },
  },
  {
    id: 'cls-6',
    cohortId: 'cohort-wia-batch-1',
    classNumber: 6,
    moduleNumber: 1,
    title: 'Review of Fundamentals & Week 1–3 Integration',
    subtitle: 'Block 1 - History & Fundamentals Review',
    description: 'Live synthesis workshop with Acharya Niraj Kumar. Q&A on karma, calendar mechanics, and foundational concepts.',
    scheduledStartTime: '2026-10-18T14:30:00.000Z',
    durationMinutes: 85,
    meetingPlatform: 'ZOOM',
    joinUrl: 'https://zoom.us/j/98142385102?pwd=VIAR_CLASS_06_PLACEHOLDER',
    meetingId: '981 4238 5102',
    passcode: 'VIAR2026',
    status: 'COMPLETED',
    recording: {
      id: 'rec-6',
      videoUrl: 'https://www.youtube.com/embed/dQw4w9WgXcQ',
      provider: 'YOUTUBE',
      durationMinutes: 84,
      recordedDate: '2026-10-18',
      notesMarkdown: `### Class 6: Block 1 Synthesis\n\n- Review quiz questions and conceptual check.\n- Transition to chart layouts and casting.`,
      keyTakeaways: ['You now possess the foundational cosmology needed to read charts'],
      resources: [],
    },
  },

  // BLOCK 2: WEEKS 4–6: Reading a Birth Chart (Classes 7–12)
  {
    id: 'cls-7',
    cohortId: 'cohort-wia-batch-1',
    classNumber: 7,
    moduleNumber: 2,
    title: 'North Indian vs South Indian Chart Layouts',
    subtitle: '/* PLACEHOLDER: Block 2 - Reading a Birth Chart */',
    description: '/* PLACEHOLDER */ Mastering the diamond chart (fixed houses) and the square chart (fixed signs). How to read either format instantly.',
    scheduledStartTime: '2026-10-24T14:30:00.000Z',
    durationMinutes: 75,
    meetingPlatform: 'ZOOM',
    joinUrl: 'https://zoom.us/j/98142385102?pwd=VIAR_CLASS_07_PLACEHOLDER',
    meetingId: '981 4238 5102',
    passcode: 'VIAR2026',
    status: 'COMPLETED',
    recording: {
      id: 'rec-7',
      videoUrl: 'https://www.youtube.com/embed/dQw4w9WgXcQ',
      provider: 'YOUTUBE',
      durationMinutes: 79,
      recordedDate: '2026-10-24',
      notesMarkdown: `### Class 7: Chart Geometry\n\n- North Indian: Houses are fixed. 1st house is top diamond. Numbers are Rashis.\n- South Indian: Signs are fixed clockwise from Aries. Diagonal slash marks Lagna.`,
      keyTakeaways: ['Knowing both styles opens up all traditional texts and regional styles'],
      resources: [],
    },
  },
  {
    id: 'cls-8',
    cohortId: 'cohort-wia-batch-1',
    classNumber: 8,
    moduleNumber: 2,
    title: 'The Ascendant (Lagna): The Gateway to the Soul',
    subtitle: '/* PLACEHOLDER: Block 2 - Reading a Birth Chart */',
    description: '/* PLACEHOLDER */ Why the eastern horizon at the moment of birth anchors all 12 life areas. Calculating the Lagna and degree significance.',
    scheduledStartTime: '2026-10-25T14:30:00.000Z',
    durationMinutes: 75,
    meetingPlatform: 'ZOOM',
    joinUrl: 'https://zoom.us/j/98142385102?pwd=VIAR_CLASS_08_PLACEHOLDER',
    meetingId: '981 4238 5102',
    passcode: 'VIAR2026',
    status: 'COMPLETED',
    recording: {
      id: 'rec-8',
      videoUrl: 'https://www.youtube.com/embed/dQw4w9WgXcQ',
      provider: 'YOUTUBE',
      durationMinutes: 73,
      recordedDate: '2026-10-25',
      notesMarkdown: `### Class 8: Lagna Mechanics\n\n- Lagna changes roughly every 2 hours.\n- Identifies the physical vessel, health, vitality, and life focus.`,
      keyTakeaways: ['Lagna is the primary reference frame for all chart interpretations'],
      resources: [],
    },
  },
  {
    id: 'cls-9',
    cohortId: 'cohort-wia-batch-1',
    classNumber: 9,
    moduleNumber: 2,
    title: 'The 12 Signs (Rashis) Part 1: Aries to Virgo',
    subtitle: '/* PLACEHOLDER: Block 2 - Reading a Birth Chart */',
    description: '/* PLACEHOLDER */ Deep breakdown of Mesha, Vrishabha, Mithuna, Karka, Simha, and Kanya. Elements, modalities, body correlations, and psychology.',
    scheduledStartTime: '2026-10-31T14:30:00.000Z',
    durationMinutes: 80,
    meetingPlatform: 'ZOOM',
    joinUrl: 'https://zoom.us/j/98142385102?pwd=VIAR_CLASS_09_PLACEHOLDER',
    meetingId: '981 4238 5102',
    passcode: 'VIAR2026',
    status: 'COMPLETED',
    recording: {
      id: 'rec-9',
      videoUrl: 'https://www.youtube.com/embed/dQw4w9WgXcQ',
      provider: 'YOUTUBE',
      durationMinutes: 81,
      recordedDate: '2026-10-31',
      notesMarkdown: `### Class 9: Signs 1 to 6\n\n- Individual consciousness and foundation signs.\n- Rulers: Mars, Venus, Mercury, Moon, Sun, Mercury.`,
      keyTakeaways: ['Understand the organic archetypes rather than memorizing keywords'],
      resources: [],
    },
  },
  {
    id: 'cls-10',
    cohortId: 'cohort-wia-batch-1',
    classNumber: 10,
    moduleNumber: 2,
    title: 'The 12 Signs (Rashis) Part 2: Libra to Pisces',
    subtitle: '/* PLACEHOLDER: Block 2 - Reading a Birth Chart */',
    description: '/* PLACEHOLDER */ Deep breakdown of Tula, Vrischika, Dhanu, Makara, Kumbha, and Meena. Transpersonal life stages and cosmic dissolution.',
    scheduledStartTime: '2026-11-01T14:30:00.000Z',
    durationMinutes: 80,
    meetingPlatform: 'ZOOM',
    joinUrl: 'https://zoom.us/j/98142385102?pwd=VIAR_CLASS_10_PLACEHOLDER',
    meetingId: '981 4238 5102',
    passcode: 'VIAR2026',
    status: 'COMPLETED',
    recording: {
      id: 'rec-10',
      videoUrl: 'https://www.youtube.com/embed/dQw4w9WgXcQ',
      provider: 'YOUTUBE',
      durationMinutes: 83,
      recordedDate: '2026-11-01',
      notesMarkdown: `### Class 10: Signs 7 to 12\n\n- Relational, societal, and transcendental signs.\n- Rulers: Venus, Mars (Ketu co-rule), Jupiter, Saturn, Saturn (Rahu co-rule), Jupiter.`,
      keyTakeaways: ['Notice the balance of dualities: fire-air vs earth-water'],
      resources: [],
    },
  },
  {
    id: 'cls-11',
    cohortId: 'cohort-wia-batch-1',
    classNumber: 11,
    moduleNumber: 2,
    title: 'Sign Qualities: Elements (Tattvas) & Modalities (Gunas)',
    subtitle: '/* PLACEHOLDER: Block 2 - Reading a Birth Chart */',
    description: '/* PLACEHOLDER */ Fire, Earth, Air, Water. Cardinal (Chara), Fixed (Sthira), Dual (Dwiswabhava). Assessing elemental temperament.',
    scheduledStartTime: '2026-11-07T14:30:00.000Z',
    durationMinutes: 75,
    meetingPlatform: 'GOOGLE_MEET',
    joinUrl: 'https://meet.google.com/xyz-viar-demo-placeholder',
    meetingId: 'xyz-viar-demo',
    passcode: 'VIAR2026',
    status: 'LIVE', // Simulated active session
  },
  {
    id: 'cls-12',
    cohortId: 'cohort-wia-batch-1',
    classNumber: 12,
    moduleNumber: 2,
    title: 'Mid-Course Practicum: Chart Casting & Reading Hands-On',
    subtitle: '/* PLACEHOLDER: Block 2 - Reading a Birth Chart */',
    description: '/* PLACEHOLDER */ Live chart casting session. Reading student charts, verifying Lagnas, and practicing sign identification.',
    scheduledStartTime: '2026-11-08T14:30:00.000Z',
    durationMinutes: 85,
    meetingPlatform: 'ZOOM',
    joinUrl: 'https://zoom.us/j/98142385102?pwd=VIAR_CLASS_12_PLACEHOLDER',
    meetingId: '981 4238 5102',
    passcode: 'VIAR2026',
    status: 'UPCOMING',
  },

  // BLOCK 3: WEEKS 7–9: Planets, Houses & Basic Predictions (Classes 13–18)
  {
    id: 'cls-13',
    cohortId: 'cohort-wia-batch-1',
    classNumber: 13,
    moduleNumber: 3,
    title: 'The 9 Grahas Part 1: Sun, Moon, Mars & Mercury',
    subtitle: '/* PLACEHOLDER: Block 3 - Planets, Houses & Basic Predictions */',
    description: '/* PLACEHOLDER */ Soul, Mind, Willpower, and Intellect. Natural benefics vs malefics, exaltation, debilitation, and combustions.',
    scheduledStartTime: '2026-11-14T14:30:00.000Z',
    durationMinutes: 80,
    meetingPlatform: 'ZOOM',
    joinUrl: 'https://zoom.us/j/98142385102?pwd=VIAR_CLASS_13_PLACEHOLDER',
    meetingId: '981 4238 5102',
    passcode: 'VIAR2026',
    status: 'UPCOMING',
  },
  {
    id: 'cls-14',
    cohortId: 'cohort-wia-batch-1',
    classNumber: 14,
    moduleNumber: 3,
    title: 'The 9 Grahas Part 2: Jupiter, Venus, Saturn & Nodes',
    subtitle: '/* PLACEHOLDER: Block 3 - Planets, Houses & Basic Predictions */',
    description: '/* PLACEHOLDER */ Wisdom (Guru), Refinement (Shukra), Discipline (Shani), and the karmic eclipse axis (Rahu & Ketu).',
    scheduledStartTime: '2026-11-15T14:30:00.000Z',
    durationMinutes: 80,
    meetingPlatform: 'ZOOM',
    joinUrl: 'https://zoom.us/j/98142385102?pwd=VIAR_CLASS_14_PLACEHOLDER',
    meetingId: '981 4238 5102',
    passcode: 'VIAR2026',
    status: 'UPCOMING',
  },
  {
    id: 'cls-15',
    cohortId: 'cohort-wia-batch-1',
    classNumber: 15,
    moduleNumber: 3,
    title: 'The 12 Bhavas: The Theatres of Human Experience',
    subtitle: '/* PLACEHOLDER: Block 3 - Planets, Houses & Basic Predictions */',
    description: '/* PLACEHOLDER */ Kendra (pillars), Trikona (grace), Dusthana (trials), and Upachaya (growth) houses. Mapping career, wealth, and destiny.',
    scheduledStartTime: '2026-11-21T14:30:00.000Z',
    durationMinutes: 80,
    meetingPlatform: 'ZOOM',
    joinUrl: 'https://zoom.us/j/98142385102?pwd=VIAR_CLASS_15_PLACEHOLDER',
    meetingId: '981 4238 5102',
    passcode: 'VIAR2026',
    status: 'UPCOMING',
  },
  {
    id: 'cls-16',
    cohortId: 'cohort-wia-batch-1',
    classNumber: 16,
    moduleNumber: 3,
    title: 'Planetary Aspects (Drishtis) & Mutual Interactions',
    subtitle: '/* PLACEHOLDER: Block 3 - Planets, Houses & Basic Predictions */',
    description: '/* PLACEHOLDER */ Standard 7th aspects and special aspects of Mars (4, 8), Jupiter (5, 9), and Saturn (3, 10). Conjunction energies.',
    scheduledStartTime: '2026-11-22T14:30:00.000Z',
    durationMinutes: 75,
    meetingPlatform: 'ZOOM',
    joinUrl: 'https://zoom.us/j/98142385102?pwd=VIAR_CLASS_16_PLACEHOLDER',
    meetingId: '981 4238 5102',
    passcode: 'VIAR2026',
    status: 'UPCOMING',
  },
  {
    id: 'cls-17',
    cohortId: 'cohort-wia-batch-1',
    classNumber: 17,
    moduleNumber: 3,
    title: 'The 5-Step Synthesis: Making Basic Predictions',
    subtitle: '/* PLACEHOLDER: Block 3 - Planets, Houses & Basic Predictions */',
    description: '/* PLACEHOLDER */ How to synthesize Lagna, Moon, Sun, 10th Lord, and Dasha to make grounded, non-fatalistic predictions.',
    scheduledStartTime: '2026-11-28T14:30:00.000Z',
    durationMinutes: 90,
    meetingPlatform: 'ZOOM',
    joinUrl: 'https://zoom.us/j/98142385102?pwd=VIAR_CLASS_17_PLACEHOLDER',
    meetingId: '981 4238 5102',
    passcode: 'VIAR2026',
    status: 'UPCOMING',
  },
  {
    id: 'cls-18',
    cohortId: 'cohort-wia-batch-1',
    classNumber: 18,
    moduleNumber: 3,
    title: 'Course Finale, Ethics & Final Graded Quiz Briefing',
    subtitle: '/* PLACEHOLDER: Block 3 - Planets, Houses & Basic Predictions */',
    description: '/* PLACEHOLDER */ Consultation ethics, empowering clients without fear, exam preparation, and certificate issuance procedure.',
    scheduledStartTime: '2026-11-29T14:30:00.000Z',
    durationMinutes: 90,
    meetingPlatform: 'ZOOM',
    joinUrl: 'https://zoom.us/j/98142385102?pwd=VIAR_CLASS_18_PLACEHOLDER',
    meetingId: '981 4238 5102',
    passcode: 'VIAR2026',
    status: 'UPCOMING',
  },
];

/* PLACEHOLDER: 20-Question Final Graded Quiz */
export const INITIAL_FINAL_TEST: FinalTest = {
  id: 'test-wia-final',
  cohortId: 'cohort-wia-batch-1',
  courseId: 'course-what-is-astrology',
  title: 'What is Astrology — Final Graded Certification Quiz',
  description: '/* PLACEHOLDER */ 20 multiple-choice questions assessing your understanding across Weeks 1–3, Weeks 4–6, and Weeks 7–9. Passing (70%+) automatically awards your certificate.',
  passingPercentage: 70,
  durationMinutes: 45,
  totalQuestions: 20,
  questions: [
    {
      id: 'q1',
      questionNumber: 1,
      topic: 'History & Fundamentals',
      question: 'In Vedic Astrology (Jyotish), which zodiac system is utilized, and why?',
      options: [
        'Tropical (Sayana) zodiac, because it aligns with earthly seasons',
        'Sidereal (Nirayana) zodiac, because it accounts for the precession of equinoxes (Ayanamsha)',
        'Heliocentric zodiac, centered exclusively on the Sun',
        'Equinoctial zodiac, where days and nights are permanently equal',
      ],
      correctOptionIndex: 1,
      explanation: 'Vedic Jyotish uses the Sidereal (Nirayana) zodiac which incorporates Ayanamsha (precession of the equinoxes) to correspond with actual astronomical star positions.',
    },
    {
      id: 'q2',
      questionNumber: 2,
      topic: 'Birth Chart Reading',
      question: 'In a North Indian diamond birth chart (Kundali), which element is permanently fixed?',
      options: [
        'The Zodiac Signs (Rashis)',
        'The Planets (Grahas)',
        'The Houses (Bhavas)',
        'The Degrees of the Ascendant',
      ],
      correctOptionIndex: 2,
      explanation: 'In the North Indian layout, Houses are fixed in space, with House 1 always in the top center diamond. Numbers inside indicate Signs.',
    },
    {
      id: 'q3',
      questionNumber: 3,
      topic: 'History & Fundamentals',
      question: 'Which type of Karma is mapped specifically and experienced as destiny in the natal birth chart?',
      options: [
        'Sanchita Karma (the total unmanifested storehouse)',
        'Prarabdha Karma (the activated karma allotted for this lifetime)',
        'Kriyamana Karma (current instant actions being created)',
        'Agami Karma (future planned actions)',
      ],
      correctOptionIndex: 1,
      explanation: 'Prarabdha Karma is that portion of the soul’s total accumulated karma that has ripened to be experienced in the present incarnation.',
    },
    {
      id: 'q4',
      questionNumber: 4,
      topic: 'History & Fundamentals',
      question: 'A Tithi (lunar day) is calculated based on which astronomical measurement?',
      options: [
        'Each 24-hour solar day from sunrise to sunrise',
        'Each 13°20\' arc of the Moon in a Nakshatra',
        'Each 12° angular longitudinal separation between the Moon and the Sun',
        'The Moon passing through the Meridian',
      ],
      correctOptionIndex: 2,
      explanation: 'A Tithi is precisely 12 degrees of longitudinal distance between the Moon and the Sun.',
    },
    {
      id: 'q5',
      questionNumber: 5,
      topic: 'Planets & Houses',
      question: 'In which zodiac sign and degree does Surya (the Sun) attain its highest exaltation (Paramochha)?',
      options: [
        'Leo at 1°',
        'Aries at 10°',
        'Sagittarius at 15°',
        'Capricorn at 28°',
      ],
      correctOptionIndex: 1,
      explanation: 'The Sun is exalted in Aries (Mesha), reaching its deepest exaltation at 10 degrees.',
    },
    {
      id: 'q6',
      questionNumber: 6,
      topic: 'Planets & Houses',
      question: 'Which houses are designated as the Kendra (pillar) houses in a birth chart?',
      options: [
        'Houses 1, 4, 7, and 10',
        'Houses 1, 5, and 9',
        'Houses 3, 6, 10, and 11',
        'Houses 6, 8, and 12',
      ],
      correctOptionIndex: 0,
      explanation: 'Houses 1, 4, 7, and 10 are the Kendra houses (pillars of action and worldly sustenance).',
    },
    {
      id: 'q7',
      questionNumber: 7,
      topic: 'Planets & Houses',
      question: 'Houses 6, 8, and 12 are known in Vedic astrology as:',
      options: [
        'Trikona houses (Houses of Grace)',
        'Dusthana houses (Houses of Struggle, Transformation, and Loss)',
        'Upachaya houses (Houses of Growth)',
        'Maraka houses (Death-inflicting houses)',
      ],
      correctOptionIndex: 1,
      explanation: 'Houses 6, 8, and 12 are classified as Dusthana houses governing challenges, transformation, and liberation.',
    },
    {
      id: 'q8',
      questionNumber: 8,
      topic: 'Birth Chart Reading',
      question: 'Which of the following sets of signs belongs to the Water element (Jala Tattva)?',
      options: [
        'Taurus, Virgo, Capricorn',
        'Aries, Leo, Sagittarius',
        'Cancer, Scorpio, Pisces',
        'Gemini, Libra, Aquarius',
      ],
      correctOptionIndex: 2,
      explanation: 'Cancer (Karka), Scorpio (Vrischika), and Pisces (Meena) are the three Water signs.',
    },
    {
      id: 'q9',
      questionNumber: 9,
      topic: 'Planets & Houses',
      question: 'Which planet co-rules Scorpio (Vrischika) alongside Mars, according to classical tradition?',
      options: [
        'Rahu',
        'Ketu',
        'Saturn',
        'Jupiter',
      ],
      correctOptionIndex: 1,
      explanation: 'In classical Parashari Jyotish, Ketu is recognized as the co-ruler of Scorpio.',
    },
    {
      id: 'q10',
      questionNumber: 10,
      topic: 'Planets & Houses',
      question: 'Which special aspects (Drishtis) does Mangala (Mars) cast in addition to its 7th house aspect?',
      options: [
        '3rd and 10th houses from itself',
        '5th and 9th houses from itself',
        '4th and 8th houses from itself',
        '2nd and 12th houses from itself',
      ],
      correctOptionIndex: 2,
      explanation: 'Mars casts special full aspects on the 4th and 8th houses from its placement.',
    },
    {
      id: 'q11',
      questionNumber: 11,
      topic: 'Planets & Houses',
      question: 'Which planet casts full divine trinal aspects on the 5th and 9th houses from its placement?',
      options: [
        'Saturn (Shani)',
        'Jupiter (Guru)',
        'Venus (Shukra)',
        'Mercury (Budha)',
      ],
      correctOptionIndex: 1,
      explanation: 'Guru (Jupiter) casts full trinal aspects on the 5th and 9th houses from where it sits.',
    },
    {
      id: 'q12',
      questionNumber: 12,
      topic: 'Planets & Houses',
      question: 'Which planet is regarded as the Manokaraka (significator of the human mind and emotions)?',
      options: [
        'Surya (Sun)',
        'Chandra (Moon)',
        'Budha (Mercury)',
        'Guru (Jupiter)',
      ],
      correctOptionIndex: 1,
      explanation: 'The Moon (Chandra) is the significator (Karaka) for the mind, psychological state, and emotional perception.',
    },
    {
      id: 'q13',
      questionNumber: 13,
      topic: 'Birth Chart Reading',
      question: 'Approximately how often does the Ascendant (Lagna) sign change on the eastern horizon?',
      options: [
        'Every 2 hours',
        'Every 24 hours',
        'Every 2.5 days',
        'Every 30 days',
      ],
      correctOptionIndex: 0,
      explanation: 'Because the Earth rotates 360 degrees in approximately 24 hours, each of the 12 signs rises for roughly 2 hours.',
    },
    {
      id: 'q14',
      questionNumber: 14,
      topic: 'Planets & Houses',
      question: 'In which sign is Guru (Jupiter) debilitated (Neecha)?',
      options: [
        'Cancer',
        'Capricorn',
        'Gemini',
        'Virgo',
      ],
      correctOptionIndex: 1,
      explanation: 'Jupiter is exalted in Cancer and debilitated in Capricorn (Makara).',
    },
    {
      id: 'q15',
      questionNumber: 15,
      topic: 'Planets & Houses',
      question: 'Which house is primarily inspected to analyze a native\'s career, public status, and profession?',
      options: [
        '6th House',
        '7th House',
        '10th House (Karma Bhava)',
        '11th House',
      ],
      correctOptionIndex: 2,
      explanation: 'The 10th House (Karma Bhava) represents career, public standing, and accomplishments.',
    },
    {
      id: 'q16',
      questionNumber: 16,
      topic: 'Planets & Houses',
      question: 'The Trikona houses (1, 5, and 9) belong to which Purushartha (aim of life)?',
      options: [
        'Dharma (Purpose & Soul Duty)',
        'Artha (Wealth and Material Security)',
        'Kama (Desire and Relationships)',
        'Moksha (Liberation and Detachment)',
      ],
      correctOptionIndex: 0,
      explanation: 'Houses 1, 5, and 9 are the Dharma Trikonas representing spiritual merit and sacred duty.',
    },
    {
      id: 'q17',
      questionNumber: 17,
      topic: 'Planets & Houses',
      question: 'Astronomically and energetically, what are Rahu and Ketu in Vedic astrology?',
      options: [
        'Moons of Saturn',
        'The mathematical intersection nodes of the Moon’s orbital path and the Sun’s ecliptic',
        'Asteroids between Mars and Jupiter',
        'Stars in the Orion constellation',
      ],
      correctOptionIndex: 1,
      explanation: 'Rahu and Ketu are the North and South Lunar Nodes where eclipses occur.',
    },
    {
      id: 'q18',
      questionNumber: 18,
      topic: 'Planets & Houses',
      question: 'What occurs when a planet is "Combust" (Asta)?',
      options: [
        'It is in an enemy sign',
        'It is retrograding backwards',
        'It is within close degree proximity to the Sun, causing its ray visibility to be obscured',
        'It is placed in the 8th house',
      ],
      correctOptionIndex: 2,
      explanation: 'Combustion occurs when a planet comes within close degrees of the Sun.',
    },
    {
      id: 'q19',
      questionNumber: 19,
      topic: 'Ethics & Consultation',
      question: 'What is the primary ethical responsibility of a Vedic astrologer according to Acharya Niraj Kumar?',
      options: [
        'To instill fear of upcoming malefic periods',
        'To demonstrate intellectual superiority by predicting fatal events',
        'To illuminate karmic patterns compassionately, restore agency, and provide uplifting guidance',
        'To state that human free will is completely nonexistent',
      ],
      correctOptionIndex: 2,
      explanation: 'Astrology is a sacred light to restore clarity, compassionate agency, and purposeful guidance.',
    },
    {
      id: 'q20',
      questionNumber: 20,
      topic: 'Basic Predictions',
      question: 'What is the correct first step when opening any birth chart in the 5-Step Synthesis method?',
      options: [
        'Immediately look at the 8th house for crises',
        'Identify the Lagna (Ascendant), its sign, degree, and locate the placement of the Lagna Lord (Lagnesha)',
        'Check Saturn\'s transit over the Moon',
        'Check the Nakshatra of Mars',
      ],
      correctOptionIndex: 1,
      explanation: 'The foundation of all chart interpretation begins with the Lagna and the Lagna Lord.',
    },
  ],
};

/* PLACEHOLDER: Demo users */
export const DEMO_USERS: User[] = [
  {
    id: 'user-student-demo',
    name: 'Aarav Sharma',
    email: 'student@example.com',
    role: 'STUDENT',
    timezone: 'Asia/Kolkata',
    avatarUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?q=80&w=200&auto=format&fit=crop',
    enrolledCohortIds: ['cohort-wia-batch-1'],
  },
  {
    id: 'user-admin-demo',
    name: 'Acharya Niraj Kumar',
    email: 'ask@aapkaastro.com',
    role: 'OWNER',
    isOwner: true,
    timezone: 'Asia/Kolkata',
    avatarUrl: '/images/Acharya_Niraj_Kumar.jpg',
    enrolledCohortIds: ['cohort-wia-batch-1'],
  },
  {
    id: 'user-staff-content',
    name: 'Priya Verma (Staff - Courses & Quizzes)',
    email: 'priya.staff@viar.in',
    role: 'ADMIN',
    isOwner: false,
    staffSections: ['courses', 'quizzes'],
    timezone: 'Asia/Kolkata',
    avatarUrl: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?q=80&w=200&auto=format&fit=crop',
    enrolledCohortIds: [],
  },
];

/* Demo certificate */
export const DEMO_CERTIFICATES: Certificate[] = [
  {
    id: 'cert-wia-9842',
    verificationCode: 'VIAR-2026-WIA-9842',
    studentId: 'user-student-demo',
    studentName: 'Aarav Sharma',
    studentEmail: 'student@example.com',
    courseId: 'course-what-is-astrology',
    courseTitle: 'What is Astrology — Foundations of Vedic Astrology',
    cohortBatchName: 'Batch 1 — Starting October 2026',
    issueDate: 'October 15, 2026',
    scorePercentage: 90,
    grade: 'Distinction',
    instructorName: 'Acharya Niraj Kumar',
    instructorTitle: 'Founder, Aapka Astro & Master Astrologer',
    verificationUrl: 'https://viar.in/verify/VIAR-2026-WIA-9842',
  },
];

/* PLACEHOLDER: Demo enrollments */
export const DEMO_ENROLLMENTS: Enrollment[] = [
  {
    id: 'enr-101',
    studentId: 'user-student-demo',
    studentName: 'Aarav Sharma',
    studentEmail: 'student@example.com',
    courseId: 'course-what-is-astrology',
    cohortId: 'cohort-wia-batch-1',
    enrolledAt: '2026-09-20T10:30:00.000Z',
    paymentStatus: 'PAID',
    paymentAmount: 4999,
    currency: 'INR',
    paymentMethod: 'UPI / Razorpay',
    paymentId: 'pay_Nz9KqP03948Viar',
  },
  {
    id: 'enr-102',
    studentId: 'user-sarah-jenkins',
    studentName: 'Sarah Jenkins',
    studentEmail: 'sarah.j@london.co.uk',
    courseId: 'course-what-is-astrology',
    cohortId: 'cohort-wia-batch-1',
    enrolledAt: '2026-09-20T14:15:00.000Z',
    paymentStatus: 'PAID',
    paymentAmount: 69,
    currency: 'USD',
    paymentMethod: 'International Card / Stripe',
    paymentId: 'ch_3M48KqP03948Stripe',
  },
  {
    id: 'enr-103',
    studentId: 'user-david-miller',
    studentName: 'David K. Miller',
    studentEmail: 'david.miller@california.com',
    courseId: 'course-what-is-astrology',
    cohortId: 'cohort-wia-batch-1',
    enrolledAt: '2026-09-21T02:40:00.000Z',
    paymentStatus: 'PAID',
    paymentAmount: 69,
    currency: 'USD',
    paymentMethod: 'Razorpay Global Card',
    paymentId: 'pay_90ViarGlobal',
  },
];
