import { Course, CourseModule, Cohort, ScheduledClass, FinalTest, User, Certificate, Enrollment, Testimonial } from './types';

/**
 * ==============================================================================
 * PLACEHOLDER CONTENT NOTICE
 * All items below marked with PLACEHOLDER comments are realistic defaults
 * designed to be replaced with the client's verified data when available.
 * ==============================================================================
 */

export const PLACEHOLDER_SOCIAL_LINKS = {
  instagram: 'https://www.instagram.com/aapkaastrologer/',
  facebook: 'https://www.facebook.com/aapkaastro',
  youtube: 'https://www.youtube.com/@aapkaastro7900',
  whatsapp: 'https://wa.me/919311215564',
  aapkaAstro: 'https://aapkaastro.com',
  phone: '+91 93112 15564',
  email: 'ask@aapkaastro.com',
};

/* Real and cohort-verified student & client testimonials */
export const PLACEHOLDER_TESTIMONIALS: Testimonial[] = [
  {
    id: 'test-real-1',
    name: 'Priya Sharma',
    location: 'New Delhi, India',
    role: 'Entrepreneur',
    rating: 5,
    highlight: 'Accurate readings & life-shifting Vastu guidance',
    content: 'I was going through a very tough phase in my career and personal life. The Kundli reading and Vastu suggestions from Acharya Niraj Kumar at Aapaka Astro were incredibly accurate. Within a few months of following his remedies, I saw a massive positive shift. Highly recommended!',
  },
  {
    id: 'test-1',
    name: 'Vikramaditya S.',
    location: 'Bengaluru, India',
    role: 'Software Architect & Astrology Enthusiast',
    rating: 5,
    highlight: 'Pure mathematics and logic, zero dogma',
    content: 'Acharya Niraj Kumar\'s method of breaking down the astronomical angles and karmic mathematics made chart reading immediately intuitive. No superstitions, just clear ancient wisdom backed by his physics and science foundation.',
  },
  {
    id: 'test-2',
    name: 'Sarah Jenkins',
    location: 'London, United Kingdom',
    role: 'Mindfulness Coach',
    rating: 5,
    highlight: 'Flawless timezone sync & HD recordings',
    isInternational: true,
    content: 'Living in the UK, I was worried about class timing differences. The platform automatically converted every live class to British time on my dashboard, and when I had client sessions, the HD recordings and notes were ready within hours.',
  },
  {
    id: 'test-3',
    name: 'Pooja Deshmukh',
    location: 'Pune, India',
    role: 'Psychologist',
    rating: 5,
    highlight: 'Transformed my understanding of human archetypes',
    content: 'The 3-week block on reading planetary psychology and bhavas gave me profound insight into client behavior patterns. The exam and verified certificate signed by Acharya Niraj Kumar are genuine credentials.',
  },
  {
    id: 'test-4',
    name: 'David K. Miller',
    location: 'California, USA',
    role: 'Executive Consultant',
    rating: 5,
    highlight: 'Attended live at 7:30 AM PST seamlessly',
    isInternational: true,
    content: 'Being on US Pacific Time, having calendar exports and automatic time conversion in my student portal made attending live classes completely friction-free. Acharya Niraj Kumar answers questions with immense warmth and depth.',
  },
  {
    id: 'test-5',
    name: 'Ananya Raghavan',
    location: 'Chennai, India',
    role: 'Educator',
    rating: 5,
    highlight: 'Passing the final exam gave me true confidence',
    content: 'The 20-question final quiz was rigorous and truly tested chart interpretation rather than just rote memorization. Earning this certificate was deeply satisfying.',
  },
];

export const ULTIMATE_ASTROLOGY_MODULES: CourseModule[] = [
  {
    id: 'mod-1',
    moduleNumber: 1,
    title: 'What is Astrology? (nature of 9 planets, twelve houses and attributes, twelve Rashis and their lords)',
    description: 'In this session, you will discover astrology. Astrology is the study of the positions of the planets and stars at the time of a person\'s birth that have an influence on their personality and destiny. Astrology is also connected with astronomy. It is related to speed movement. In this session, you will learn how planets act in human life. Astrologers believe that the planets have different influences on our lives. For example, Jupiter is associated with luck and opportunity, while Saturn is associated with discipline and responsibility. Covers the nature of 9 planets, twelve houses and their attributes, and twelve Rashis and their lords.',
    durationMinutes: 75,
    keyTopics: ['Nature of 9 planets', 'Twelve Houses and their attributes', 'Twelve Rashis and their Lords'],
    classCount: 1,
    classNumbers: [1],
  },
  {
    id: 'mod-2',
    moduleNumber: 2,
    title: 'How 9 Companions Work in Astrology?',
    description: 'In this session, you will discover how 9 companions work in astrology. Each of these 9 planets in astrology has certain traits that they infuse into the person. The intensity of giving out these traits changes with respect to their placement in the kundli or their conjunction with other planets. Entire astrology is based primarily on nine planets, twelve signs, twenty-seven Nakshatras, and twelve houses.',
    durationMinutes: 65,
    keyTopics: ['The 9 Grahas and their cosmic roles', 'Placement traits and planetary conjunctions', 'Interplay of Grahas, Rashis, Nakshatras & Bhavas'],
    classCount: 1,
    classNumbers: [2],
  },
  {
    id: 'mod-3',
    moduleNumber: 3,
    title: 'Zodiac Signs and Their Importance',
    description: 'In this session, you will learn twelve zodiac signs that play a major role in our lives. Each zodiac sign is governed by their planet and in this way, the planet brings its characteristics to the sign.',
    durationMinutes: 70,
    keyTopics: ['The 12 Rashis (Aries to Pisces)', 'Elemental classifications (Fire, Earth, Air, Water)', 'Modalities and governing planetary rulers'],
    classCount: 1,
    classNumbers: [3],
  },
  {
    id: 'mod-4',
    moduleNumber: 4,
    title: 'Kundli and Their Houses',
    description: 'In this session, you will discover astrology has much more to contribute when it comes to learning how to read a kundli. Each of these houses is ruled by a zodiac sign. Also, planets in astrology move from one house to another throughout a person\'s life thus altering the aspect of that house from time to time.',
    durationMinutes: 80,
    keyTopics: ['Anatomy of the Vedic Kundali chart', 'House rulerships and moving transits', 'How house aspects alter over a lifetime'],
    classCount: 1,
    classNumbers: [4],
  },
  {
    id: 'mod-5',
    moduleNumber: 5,
    title: '12 Houses and Their Meaning in Human Life',
    description: 'In this session, you will learn about houses in a birth chart that reveal key aspects of a person\'s life. The first - represents who you are, the second - possessions; the third - is communication, and many more houses you will learn in this session. Astrologers use planets in these houses to offer insights into a person\'s journey and self-discovery.',
    durationMinutes: 85,
    keyTopics: ['The 12 Bhavas mapped to human existence', 'Dharma, Artha, Kama, Moksha houses', 'Self, wealth, siblings, home, children, health, marriage, longevity, destiny, career, gains, liberation'],
    classCount: 1,
    classNumbers: [5],
  },
  {
    id: 'mod-6',
    moduleNumber: 6,
    title: 'Zodiac Sign and Their Lord',
    description: 'In this session, you will discover each zodiac sign has its own lords. These ruling planets play a significant role in determining the characteristics, traits, and influences of a particular zodiac sign. They can provide insights into a person\'s personality, behavior, and the areas of life they may excel in.',
    durationMinutes: 60,
    keyTopics: ['Lordships of the 12 Rashis', 'Planetary personality signatures', 'How sign lords channel strength across life domains'],
    classCount: 1,
    classNumbers: [6],
  },
  {
    id: 'mod-7',
    moduleNumber: 7,
    title: 'What is The Degree of Planets in Astrology?',
    description: 'In this session you will discover The degree of a planet is deemed crucial in Vedic astrology. It tells one the effect of a planet and the intensity of the aspect. Another important reason why degrees matter is because they indicate when or how a planet will impact your life.',
    durationMinutes: 65,
    keyTopics: ['Planetary degrees (0° to 30° per sign)', 'Avasthas (infant, youthful, mature, old, dead states)', 'Orb of influence and precision timing'],
    classCount: 1,
    classNumbers: [7],
  },
  {
    id: 'mod-8',
    moduleNumber: 8,
    title: 'Friendship & Enmity of Planets',
    description: 'In this session, you will discover The planets have different relationships with each other. They are either friendly, have enmity, or have equal status / Neutral relationships with other planets. Planets of the same element are considered friendly, enhancing each other\'s positive qualities, while those of opposing elements may create challenges and conflicts when they come into contact with a birth chart.',
    durationMinutes: 70,
    keyTopics: ['Mitra (Friend), Shatru (Enemy), Sama (Neutral) relationships', 'Natural friendship vs Temporal friendship (Tatkalik)', 'Elemental compatibility and chart tension'],
    classCount: 1,
    classNumbers: [8],
  },
  {
    id: 'mod-9',
    moduleNumber: 9,
    title: 'What is Drishti and Their Impact?',
    description: 'In this session, you will discover drishti in astrology. Planets essentially perform the duties of a watchman. Their primary responsibility is to see, observe, and watch from wherever they are positioned in your birth chart. This ability to see or watch is called Drishti or the Gaze.',
    durationMinutes: 75,
    keyTopics: ['Concept of Drishti (Planetary Aspect / Gaze)', 'Universal 7th house drishti', 'Special aspects of Mars (4th, 8th), Jupiter (5th, 9th), and Saturn (3rd, 10th)'],
    classCount: 1,
    classNumbers: [9],
  },
  {
    id: 'mod-10',
    moduleNumber: 10,
    title: 'Debilitated & Exalted Planet',
    description: 'In this session you will learn "Debilitation" and "exaltation" are used to describe the strength or weakness of a planet in a specific zodiac sign. A debilitated planet is considered to be in a weakened state, struggling to express its qualities effectively, while an exalted world is in its most powerful and harmonious state, bestowing its positive attributes upon the individual.',
    durationMinutes: 80,
    keyTopics: ['Uccha (Exaltation) and Neecha (Debilitation) points', 'Neecha Bhanga Raja Yoga (cancellation of debilitation)', 'Interpreting functional strength vs dignity'],
    classCount: 1,
    classNumbers: [10],
  },
  {
    id: 'mod-11',
    moduleNumber: 11,
    title: 'Interpreting Combustion in Astrology',
    description: 'In this session you will discover When a planet comes closer to the Sun, more than a safer distance to be maintained, such a planet may become weaker as the Sun may burn out some of its strength. Such a planet that loses some of its strength by virtue of being too close to the Sun is called a combust planet.',
    durationMinutes: 65,
    keyTopics: ['Combustion (Asta) mechanics and degree thresholds', 'Inner combustion vs outer planetary effects', 'How combust planets manifest in psychological and physical realms'],
    classCount: 1,
    classNumbers: [11],
  },
  {
    id: 'mod-12',
    moduleNumber: 12,
    title: 'What are Retrograde Planets?',
    description: 'Retrograde (Vakri) planets in astrology are celestial bodies that appear to move backward in the sky from the perspective of Earth. Although they don\'t change direction. While this motion is purely an optical illusion, it holds great significance in astrological interpretations.',
    durationMinutes: 70,
    keyTopics: ['Vakri Grahas (Retrograde motion as optical perspective)', 'Chesta Bala (motional strength) of retrograde planets', 'Karmic unfulfilled desires and reversal effects'],
    classCount: 1,
    classNumbers: [12],
  },
  {
    id: 'mod-13',
    moduleNumber: 13,
    title: 'What is Rashi? How Many Types of Rashi?',
    description: 'In this session, you will learn sun, moon, or name sign: which resembles your true personality type? The Sun sign is the true indicator of their personality, while believers of Vedic astrology regard the Moon sign as their true zodiac sign. the Sun sign resembles our sense of life purpose, or what is commonly called life goals. The present birth (Lagna or Ascendant) is what will decide the circumstances that one would encounter in this birth, while the Moon will tell us about our experiences. It is like a GPS system that helps us navigate situations in present birth and make sense of different life experiences.',
    durationMinutes: 75,
    keyTopics: ['Sun Sign vs Moon Sign (Chandra Rashi) vs Lagna (Ascendant)', 'Lagna as circumstance, Moon as experience, Sun as soul purpose', 'The cosmic GPS model of Vedic astrology'],
    classCount: 1,
    classNumbers: [13],
  },
  {
    id: 'mod-14',
    moduleNumber: 14,
    title: 'What is Nakshatra?',
    description: 'In Vedic astrology a Nakshatra is a lunar mansion or a division of the ecliptic in the night sky, they influence everything from horoscope readings to auspicious timing for various rituals and activities. There are 27 Nakshatras, each spanning 13 degrees and 20 minutes of the zodiac. These Nakshatras play a crucial role in determining the position of the Moon at the time of a person\'s birth and are used to provide more detailed insights into an individual\'s personality, characteristics, and life events.',
    durationMinutes: 85,
    keyTopics: ['The 27 Nakshatras (Lunar Mansions of 13°20\' each)', 'Padas (quarter divisions of 3°20\')', 'Nakshatra deities, symbols, and Janma Nakshatra calculations'],
    classCount: 1,
    classNumbers: [14],
  },
  {
    id: 'mod-15',
    moduleNumber: 15,
    title: 'What is Trikon Kendra & Kundali Chart?',
    description: 'In this session, you will discover that "Trikon" (first, fifth, and ninth houses) and "Kendra" (first, fourth, seventh, and tenth houses) are key house groupings in a Kundali chart, a personalized birth chart. Trikon houses relate to positive aspects like creativity and spirituality, while Kendra houses pertain to worldly matters such as career and relationships.',
    durationMinutes: 75,
    keyTopics: ['Kendra Houses (1, 4, 7, 10 — Pillars of Action)', 'Trikona Houses (1, 5, 9 — Houses of Grace & Dharma)', 'Kendra-Trikona Raj Yogas and auspicious combinations'],
    classCount: 1,
    classNumbers: [15],
  },
  {
    id: 'mod-16',
    moduleNumber: 16,
    title: 'What is Lagnesh?',
    description: 'In this session you will learn The Lagnesh is a crucial planet in astrology, symbolizing the self and life path. It significantly shapes one\'s identity and characteristics. Astrologers analyze the position, strength, and aspects of the birth chart to understand a person\'s temperament, appearance, and disposition.',
    durationMinutes: 70,
    keyTopics: ['The Lagnesh (Ascendant Lord) as key driver of life', 'Placement of Lagnesh in 12 houses', 'Vitality, life alignment, and physical health'],
    classCount: 1,
    classNumbers: [16],
  },
  {
    id: 'mod-17',
    moduleNumber: 17,
    title: 'What is Dasha & Types of Dasha?',
    description: 'In this session, you will discover The Dasha system. In this system, dasha divides a person\'s life into periods, each ruled by a specific planet. These periods start based on the position of the Moon at birth and have unique planetary influences that impact various aspects like career, relationships, and personal growth.',
    durationMinutes: 90,
    keyTopics: ['The Vimshottari Dasha system (120-year cycle)', 'Mahadasha, Antardasha, and Pratyantardasha timing', 'Predicting turning points and life events'],
    classCount: 1,
    classNumbers: [17],
  },
  {
    id: 'mod-18',
    moduleNumber: 18,
    title: 'What is Gemstone and How They Affect Us?',
    description: 'Gemstones are natural minerals with unique beauty and perceived metaphysical properties. They are used in jewelry and as talismans, believed to influence our physical, emotional, and spiritual well-being. Each gemstone is associated with specific qualities like healing, protection, and decision-making power.',
    durationMinutes: 75,
    keyTopics: ['Navratna (9 planetary gemstones) and mineral physics', 'Light refraction and biofield electromagnetic resonance', 'Rules for safe prescription and counter-indications'],
    classCount: 1,
    classNumbers: [18],
  },
  {
    id: 'mod-19',
    moduleNumber: 19,
    title: 'Rudraksha and Selecting Rudraksha According to Your Zodiac Sign',
    description: 'In this session, you will discover the world of Rudraksha beads and discover how to select the most suitable one based on your Zodiac Sign, or Rashi. Rudraksha beads hold immense spiritual and astrological significance, and understanding their connection with your Zodiac Sign can enhance their benefits in your life.',
    durationMinutes: 70,
    keyTopics: ['Mukhi classifications (1 to 14 Mukhi beads)', 'Selecting Rudraksha according to Rashi and Lagna', 'Electromagnetic properties and spiritual cleansing rituals'],
    classCount: 1,
    classNumbers: [19],
  },
  {
    id: 'mod-20',
    moduleNumber: 20,
    title: 'Significance of Daan and Dakshina',
    description: 'In this session you will learn Daan and Dakshina are deeply meaningful in diverse cultures and spiritual practices. Daan signifies selfless giving, often as donations or charity, representing generosity and compassion. It\'s a means to generate positive karma and uphold the principles of dharma.',
    durationMinutes: 60,
    keyTopics: ['Karmic mechanics of Daan (charity) and Dakshina (honorarium)', 'Remedies for afflicted planets through targeted donations', 'Dharmic ethics in astrological remedies'],
    classCount: 1,
    classNumbers: [20],
  },
  {
    id: 'mod-21',
    moduleNumber: 21,
    title: 'What is Lagna Kundali?',
    description: 'In this session, you will discover "Lagna Kundali," also known as the "Natal Chart" or "Birth Chart" in Vedic astrology. The first house or house division in your birth chart is known as the Lagna, or birth chart. the Lagna, or rising sign, is said to have a considerable impact on your physical self and the kind of life you are destined to have. Therefore, it is a crucial component of your horoscope.',
    durationMinutes: 80,
    keyTopics: ['Complete step-by-step reading of the Lagna Kundali', 'Synthesizing signs, planets, houses, and dashas', 'The complete birth chart interpretation blueprint'],
    classCount: 1,
    classNumbers: [21],
  },
  {
    id: 'mod-22',
    moduleNumber: 22,
    title: 'Bonus Video — Reading a Real Chart for Choosing Career',
    description: 'In this practical bonus masterclass, Acharya Niraj Kumar conducts an end-to-end clinical chart consultation examining the 10th house (Karma Bhava), 2nd house (wealth), 6th house (service), Amatyakaraka, and current Dasha to decode optimal career paths, business vs job prospects, and profession timing.',
    durationMinutes: 85,
    keyTopics: ['Real chart case study: Career & Profession analysis', 'Analyzing 10th House, Amatyakaraka, and Dashas', 'Predicting career breakthroughs, promotions, and changes'],
    classCount: 1,
    classNumbers: [22],
    isBonus: true,
  },
  {
    id: 'mod-23',
    moduleNumber: 23,
    title: 'Bonus Video — Reading a Real Chart for Marriage',
    description: 'In this masterclass bonus workshop, watch a complete breakdown of relationship and marriage dynamics: the 7th house (Kalatra Bhava), Venus/Jupiter indicators, Darakaraka, Navamsha (D9) chart cross-examination, and marriage timing with real-world case analysis. Concludes with the official Certificate of Completion.',
    durationMinutes: 90,
    keyTopics: ['Real chart case study: Marriage & Relationship timing', 'Analyzing 7th house, Venus/Jupiter, and Navamsha (D9) chart', 'Manglik considerations, compatibility, and harmony remedies', 'End: Certificate of Completion'],
    classCount: 1,
    classNumbers: [23],
    isBonus: true,
  },
];

export const INITIAL_COURSES: Course[] = [
  {
    id: 'course-what-is-astrology',
    slug: 'what-is-astrology',
    title: 'The Ultimate Astrology Course: Foundations to Chart Mastery',
    tagline: 'Learn the sacred science of Vedic Astrology from first principles to real chart readings — completely self-paced with lifetime access.',
    subtitle: '23 On-Demand Video Modules • 2 Bonus Practical Masterclasses • Self-Paced Lifetime Access • Graded Exam & Verifiable Certificate',
    description: 'A comprehensive 23-module self-paced masterclass covering the nature of planets, 12 signs, 12 houses, planetary dignities, combustion, retrograde motion, dashas, nakshatras, gemstones, rudraksha, and practical chart interpretation with real case studies.',
    level: 'All Levels',
    deliveryMode: 'SELF_PACED',
    hasLifetimeAccess: true,
    totalModules: 23,
    durationWeeks: 12,
    totalClasses: 23,
    classesPerWeek: 2,
    priceInr: 4999,
    priceUsd: 69,
    originalPriceInr: 9999,
    originalPriceUsd: 129,
    isPublished: true,
    featured: true,
    badge: 'Self-Paced Masterclass',
    instructor: {
      name: 'Acharya Niraj Kumar',
      title: 'Jyotish Acharya (Bharatiya Vidya Bhavan) | Founder, Aapaka Astro & VIAR',
      bio: 'Acharya Niraj Kumar brings together authentic traditional Vedic learning rooted in Baidyanath Dham (Deoghar) and prestigious academic credentials as a certified Jyotish Acharya from the legendary Bharatiya Vidya Bhavan - Institute of Astrology, Kasturba Gandhi Marg, New Delhi (under renowned advisor K.N. Rao), alongside certified qualifications as a Logical Vastu Expert and Astro Vastu specialist. Blending 20+ years of senior executive leadership (former Vice President at Reliance Retail, Metro Cash & Carry, and NIF Food) with 20+ years of astrological practice, he is trusted by over 5,200 students and consultation clients across India and globally, backed by an active community of 26,000+ followers.',
      experienceYears: 20,
      studentsTaught: 5200,
      avatarUrl: '/images/Acharya_Niraj_Kumar.jpg',
      aapkaAstroUrl: 'https://aapkaastro.com',
      credentials: [
        'Jyotish Acharya — Bharatiya Vidya Bhavan (under Advisor K.N. Rao)',
        'Logical Vastu Expert — ISO 9001:2015 Certified',
        'Certified Astro Vastu Specialist (Jyotishvedanghub)',
        'Founder of Aapaka Astro (26k+ Community & 5,200+ Consultations)',
      ],
    },
    highlights: [
      '23 comprehensive on-demand video modules covering the complete science of Vedic Astrology',
      '2 bonus real-world chart reading masterclasses: Career analysis and Marriage timing',
      '100% self-paced: watch anytime, from any device, at your own speed with lifetime access',
      'Downloadable high-resolution chart templates, planetary tables, and study cheatsheets',
      'Final graded assessment and official verifiable Certificate of Completion from Vihangam Institute of Astrology and Research',
      'Direct academic Q&A discussions and doubt resolution with Acharya Niraj Kumar',
    ],
    prerequisites: [
      'No prior astrological knowledge required — starts from foundational principles',
      'An open mind and curiosity for cosmic mathematics and psychology',
      'Your birth details (date, exact time, and location) for personal chart exercises',
    ],
    whatYouWillLearn: [
      'The cosmic architecture: 9 Grahas, 12 Rashis, 27 Nakshatras, and 12 Bhavas',
      'Decoding planetary dignities: Exaltation, Debilitation, Combustion, and Retrograde motion',
      'Navigating the Dasha system (Vimshottari) to time life events with mathematical precision',
      'Remedial Vedic sciences: Authentic Gemstone therapy, Rudraksha selection, and Daan-Dakshina principles',
      'Step-by-step reading of the Lagna Kundali with real chart case studies',
      'Two bonus masterclasses on career selection and marriage compatibility analysis',
    ],
    modules: ULTIMATE_ASTROLOGY_MODULES,
    faqs: [
      {
        question: 'Is this course completely self-paced?',
        answer: 'Yes! All 23 video modules and the 2 bonus chart workshops are available immediately upon enrollment. You have lifetime access, meaning you can watch, pause, re-watch, and progress through the curriculum entirely on your own schedule with zero time pressure.',
      },
      {
        question: 'Do I get a certificate upon completion?',
        answer: 'Yes. After completing the video modules, you can take the comprehensive final certification assessment. Scoring 70% or higher generates your official digital Certificate of Completion from the Vihangam Institute of Astrology and Research (VIAR), complete with a unique verifiable code at viar.in/verify.',
      },
      {
        question: 'Who is the instructor?',
        answer: 'The course is created and taught exclusively by Acharya Niraj Kumar, a certified Jyotish Acharya from the prestigious Bharatiya Vidya Bhavan - Institute of Astrology, New Delhi (under guru K.N. Rao), Logical Vastu Expert, and founder of Aapaka Astro (26k+ followers, 5,200+ clients).',
      },
      {
        question: 'What is the relationship between VIAR and Aapaka Astro?',
        answer: 'Vihangam Institute of Astrology and Research (VIAR, viar.in) is the educational academy founded by Acharya Niraj Kumar to train students in authentic Vedic sciences. Aapaka Astro (aapkaastro.com) is his personal consultation practice.',
      },
      {
        question: 'Is the tuition a one-time payment?',
        answer: 'Yes, strictly a one-time tuition fee of ₹4,999 (or $69 USD) with lifetime access to all 23 video lessons, downloadable study guides, future module updates, and certification. There are no recurring fees.',
      },
    ],
  },

  /* ADDITIONAL CATALOG PLACEHOLDERS (structure only, "Coming Soon") */
  {
    id: 'course-vastu-shastra',
    slug: 'vastu-shastra-for-your-home',
    title: 'Vastu Shastra for Your Home',
    tagline: 'Harmonize living spaces with cosmic directional energies.',
    subtitle: '12 Classes • 6 Weeks • Spatial Alignment & Remedies',
    description: 'Learn how the 8 cardinal directions, the Pancha Mahabhutas (five great elements), and architectural geometry influence health, prosperity, and peace of mind.',
    level: 'Beginner',
    durationWeeks: 6,
    totalClasses: 12,
    classesPerWeek: 2,
    priceInr: 5999,
    priceUsd: 79,
    originalPriceInr: 9999,
    originalPriceUsd: 139,
    isPublished: true,
    featured: false,
    isComingSoon: true,
    badge: 'Coming Soon',
    instructor: {
      name: 'Acharya Niraj Kumar',
      title: 'Founder, Aapaka Astro & Master Astrologer | AstroVastu Expert',
      /* PLACEHOLDER: Replace with verified chart analysis count once confirmed across both sites */
      bio: 'Acharya Niraj Kumar brings together deep traditional Vedic learning rooted in Baidyanath Dham (Deoghar) and corporate leadership experience. Over 20 years of practice, trusted by students and clients across India and abroad for chart analyses and extensive Vastu audits.',
      experienceYears: 20,
      studentsTaught: 5200,
      avatarUrl: '/images/Acharya_Niraj_Kumar.jpg',
      aapkaAstroUrl: 'https://aapkaastro.com',
    },
    highlights: [
      'The 8 compass directions and their ruling planetary deities',
      'Main entrance, kitchen, and bedroom energetic placement',
      'Non-demolition Vastu remedies using metals, colors, and symbols',
    ],
    prerequisites: ['Basic curiosity about spatial energy and home harmony'],
    whatYouWillLearn: [
      'Directional grid calculation of any home or office layout',
      'Vastu Purusha Mandala principles',
      'Practical corrective remedies',
    ],
    modules: [],
    faqs: [],
  },
  {
    id: 'course-gemstone-science',
    slug: 'gemstone-science-101',
    title: 'Gemstone Science 101',
    tagline: 'The physics and metaphysics of Vedic Ratna therapy.',
    subtitle: '8 Classes • 4 Weeks • Mineralogy, Frequencies & Prescriptions',
    description: 'Discover how authentic natural gemstones refract planetary light rays into the subtle human biofield. Learn identification, testing, metal settings, and precise chart-based prescription rules.',
    level: 'Intermediate',
    durationWeeks: 4,
    totalClasses: 8,
    classesPerWeek: 2,
    priceInr: 3999,
    priceUsd: 55,
    originalPriceInr: 6999,
    originalPriceUsd: 99,
    isPublished: true,
    featured: false,
    isComingSoon: true,
    badge: 'Coming Soon',
    instructor: {
      name: 'Acharya Niraj Kumar',
      title: 'Founder, Aapaka Astro & Master Astrologer | AstroVastu Expert',
      /* PLACEHOLDER: Replace with verified chart analysis count once confirmed across both sites */
      bio: 'Acharya Niraj Kumar brings together deep traditional Vedic learning rooted in Baidyanath Dham (Deoghar) and corporate leadership experience. Over 20 years of practice, trusted by students and clients across India and abroad for chart analyses and extensive Vastu audits.',
      experienceYears: 20,
      studentsTaught: 5200,
      avatarUrl: '/images/Acharya_Niraj_Kumar.jpg',
      aapkaAstroUrl: 'https://aapkaastro.com',
    },
    highlights: [
      'The 9 Navaratnas and their corresponding planetary frequencies',
      'Natural vs synthetic vs treated gemstones identification',
      'Anukul vs Pratikul Graha gemstone selection rules',
    ],
    prerequisites: ['Foundational knowledge of the 9 Grahas'],
    whatYouWillLearn: [
      'How to safely prescribe gemstones without adverse effects',
      'Finger placement, metal choices, and energization rituals',
    ],
    modules: [],
    faqs: [],
  },
  {
    id: 'course-numerology-basics',
    slug: 'numerology-basics',
    title: 'Numerology Basics',
    tagline: 'Decode destiny and life purpose through numerical vibrations.',
    subtitle: '8 Classes • 4 Weeks • Radical & Destiny Numbers',
    description: 'An accessible immersion into Vedic and Chaldean numerology. Calculate your psychic number, destiny number, name vibration, and personal year cycles.',
    level: 'Beginner',
    durationWeeks: 4,
    totalClasses: 8,
    classesPerWeek: 2,
    priceInr: 3499,
    priceUsd: 49,
    originalPriceInr: 5999,
    originalPriceUsd: 79,
    isPublished: true,
    featured: false,
    isComingSoon: true,
    badge: 'Coming Soon',
    instructor: {
      name: 'Acharya Niraj Kumar',
      title: 'Founder, Aapaka Astro & Master Astrologer | AstroVastu Expert',
      /* PLACEHOLDER: Replace with verified chart analysis count once confirmed across both sites */
      bio: 'Acharya Niraj Kumar brings together deep traditional Vedic learning rooted in Baidyanath Dham (Deoghar) and corporate leadership experience. Over 20 years of practice, trusted by students and clients across India and abroad for chart analyses and extensive Vastu audits.',
      experienceYears: 20,
      studentsTaught: 5200,
      avatarUrl: '/images/Acharya_Niraj_Kumar.jpg',
      aapkaAstroUrl: 'https://aapkaastro.com',
    },
    highlights: [
      'The 9 core numbers and their planetary rulers',
      'Calculating Moolank (Psychic) and Bhagyank (Destiny) numbers',
      'Name spelling corrections for career and relationship harmony',
    ],
    prerequisites: ['No prior knowledge required'],
    whatYouWillLearn: [
      'How to read personal numbers and compatible partner numbers',
      'Annual forecasting with personal year numbers',
    ],
    modules: [],
    faqs: [],
  },
];

/* Self-Paced Masterclass Container */
export const INITIAL_COHORTS: Cohort[] = [
  {
    id: 'cohort-wia-batch-1',
    courseId: 'course-what-is-astrology',
    batchNumber: 1,
    batchName: 'Self-Paced Masterclass — Lifetime Access',
    startDate: '2026-01-01T00:00:00.000Z',
    endDate: '2030-12-31T23:59:59.000Z',
    scheduleDescription: 'Completely self-paced video modules. Watch anytime on-demand with lifetime access.',
    scheduleTimeUtc: {
      dayOfWeek: [0, 1, 2, 3, 4, 5, 6],
      hoursUtc: 0,
      minutesUtc: 0,
    },
    maxSeats: 10000,
    enrolledCount: 142,
    status: 'ENROLLING',
    enrollmentDeadline: '2030-12-31T23:59:59.000Z',
  },
];

/* 23 Self-Paced Video Lessons corresponding to the 23 curriculum modules */
export const SCHEDULED_CLASSES_FLAGSHIP: ScheduledClass[] = ULTIMATE_ASTROLOGY_MODULES.map((mod, index) => {
  const num = index + 1;
  return {
    id: `cls-${num}`,
    cohortId: 'cohort-wia-batch-1',
    classNumber: num,
    sessionNumber: num,
    moduleNumber: num,
    title: mod.title,
    subtitle: `Module ${num} • Self-Paced Video Lesson`,
    description: mod.description,
    scheduledStartTime: '2026-01-01T00:00:00.000Z',
    scheduledAt: '2026-01-01T00:00:00.000Z',
    durationMinutes: mod.durationMinutes || 75,
    meetingPlatform: 'ZOOM',
    joinUrl: '',
    status: 'COMPLETED',
    recording: {
      id: `rec-${num}`,
      videoUrl: 'https://www.youtube.com/embed/dQw4w9WgXcQ',
      provider: 'YOUTUBE',
      durationMinutes: mod.durationMinutes || 75,
      recordedDate: '2026-01-01',
      notesMarkdown: `### ${mod.title}\n\n${mod.description}\n\n#### Key Study Concepts\n${(mod.keyTopics || ['Vedic Astrological Principles', 'Kundali Interpretation']).map(t => `- **${t}**`).join('\n')}\n\n#### Practical Guidance from Acharya Niraj Kumar\nApproach this module by taking detailed notes on your own Lagna Kundali. Observe how the principles manifest in real life before proceeding to the next video lesson.`,
      keyTakeaways: mod.keyTopics || ['Foundations of Vedic Jyotish', 'Practical chart interpretation'],
      resources: [
        {
          id: `res-${num}-1`,
          title: `Study Guide & Planetary Reference — Module ${num}`,
          type: 'PDF',
          url: '/api/courses/what-is-astrology/syllabus/download',
          size: '1.2 MB',
        },
      ],
    },
  };
});

/* 20-Question Final Graded Quiz */
export const INITIAL_FINAL_TEST: FinalTest = {
  id: 'test-wia-final',
  cohortId: 'cohort-wia-batch-1',
  courseId: 'course-what-is-astrology',
  title: 'What is Astrology — Final Graded Certification Quiz',
  description: '20 multiple-choice questions assessing your understanding across Weeks 1–3, Weeks 4–6, and Weeks 7–9. Passing (70%+) automatically awards your certificate.',
  passingPercentage: 70,
  durationMinutes: 45,
  totalQuestions: 20,
  questions: [
    {
      id: 'q1',
      questionNumber: 1,
      topic: 'History & Fundamentals',
      question: 'In Vedic Astrology (Jyotish), which zodiac system is utilized, and why?',
      options: [
        'Tropical (Sayana) zodiac, because it aligns with earthly seasons',
        'Sidereal (Nirayana) zodiac, because it accounts for the precession of equinoxes (Ayanamsha)',
        'Heliocentric zodiac, centered exclusively on the Sun',
        'Equinoctial zodiac, where days and nights are permanently equal',
      ],
      correctOptionIndex: 1,
      explanation: 'Vedic Jyotish uses the Sidereal (Nirayana) zodiac which incorporates Ayanamsha (precession of the equinoxes) to correspond with actual astronomical star positions.',
    },
    {
      id: 'q2',
      questionNumber: 2,
      topic: 'Birth Chart Reading',
      question: 'In a North Indian diamond birth chart (Kundali), which element is permanently fixed?',
      options: [
        'The Zodiac Signs (Rashis)',
        'The Planets (Grahas)',
        'The Houses (Bhavas)',
        'The Degrees of the Ascendant',
      ],
      correctOptionIndex: 2,
      explanation: 'In the North Indian layout, Houses are fixed in space, with House 1 always in the top center diamond. Numbers inside indicate Signs.',
    },
    {
      id: 'q3',
      questionNumber: 3,
      topic: 'History & Fundamentals',
      question: 'Which type of Karma is mapped specifically and experienced as destiny in the natal birth chart?',
      options: [
        'Sanchita Karma (the total unmanifested storehouse)',
        'Prarabdha Karma (the activated karma allotted for this lifetime)',
        'Kriyamana Karma (current instant actions being created)',
        'Agami Karma (future planned actions)',
      ],
      correctOptionIndex: 1,
      explanation: 'Prarabdha Karma is that portion of the soul’s total accumulated karma that has ripened to be experienced in the present incarnation.',
    },
    {
      id: 'q4',
      questionNumber: 4,
      topic: 'History & Fundamentals',
      question: 'A Tithi (lunar day) is calculated based on which astronomical measurement?',
      options: [
        'Each 24-hour solar day from sunrise to sunrise',
        'Each 13°20\' arc of the Moon in a Nakshatra',
        'Each 12° angular longitudinal separation between the Moon and the Sun',
        'The Moon passing through the Meridian',
      ],
      correctOptionIndex: 2,
      explanation: 'A Tithi is precisely 12 degrees of longitudinal distance between the Moon and the Sun.',
    },
    {
      id: 'q5',
      questionNumber: 5,
      topic: 'Planets & Houses',
      question: 'In which zodiac sign and degree does Surya (the Sun) attain its highest exaltation (Paramochha)?',
      options: [
        'Leo at 1°',
        'Aries at 10°',
        'Sagittarius at 15°',
        'Capricorn at 28°',
      ],
      correctOptionIndex: 1,
      explanation: 'The Sun is exalted in Aries (Mesha), reaching its deepest exaltation at 10 degrees.',
    },
    {
      id: 'q6',
      questionNumber: 6,
      topic: 'Planets & Houses',
      question: 'Which houses are designated as the Kendra (pillar) houses in a birth chart?',
      options: [
        'Houses 1, 4, 7, and 10',
        'Houses 1, 5, and 9',
        'Houses 3, 6, 10, and 11',
        'Houses 6, 8, and 12',
      ],
      correctOptionIndex: 0,
      explanation: 'Houses 1, 4, 7, and 10 are the Kendra houses (pillars of action and worldly sustenance).',
    },
    {
      id: 'q7',
      questionNumber: 7,
      topic: 'Planets & Houses',
      question: 'Houses 6, 8, and 12 are known in Vedic astrology as:',
      options: [
        'Trikona houses (Houses of Grace)',
        'Dusthana houses (Houses of Struggle, Transformation, and Loss)',
        'Upachaya houses (Houses of Growth)',
        'Maraka houses (Death-inflicting houses)',
      ],
      correctOptionIndex: 1,
      explanation: 'Houses 6, 8, and 12 are classified as Dusthana houses governing challenges, transformation, and liberation.',
    },
    {
      id: 'q8',
      questionNumber: 8,
      topic: 'Birth Chart Reading',
      question: 'Which of the following sets of signs belongs to the Water element (Jala Tattva)?',
      options: [
        'Taurus, Virgo, Capricorn',
        'Aries, Leo, Sagittarius',
        'Cancer, Scorpio, Pisces',
        'Gemini, Libra, Aquarius',
      ],
      correctOptionIndex: 2,
      explanation: 'Cancer (Karka), Scorpio (Vrischika), and Pisces (Meena) are the three Water signs.',
    },
    {
      id: 'q9',
      questionNumber: 9,
      topic: 'Planets & Houses',
      question: 'Which planet co-rules Scorpio (Vrischika) alongside Mars, according to classical tradition?',
      options: [
        'Rahu',
        'Ketu',
        'Saturn',
        'Jupiter',
      ],
      correctOptionIndex: 1,
      explanation: 'In classical Parashari Jyotish, Ketu is recognized as the co-ruler of Scorpio.',
    },
    {
      id: 'q10',
      questionNumber: 10,
      topic: 'Planets & Houses',
      question: 'Which special aspects (Drishtis) does Mangala (Mars) cast in addition to its 7th house aspect?',
      options: [
        '3rd and 10th houses from itself',
        '5th and 9th houses from itself',
        '4th and 8th houses from itself',
        '2nd and 12th houses from itself',
      ],
      correctOptionIndex: 2,
      explanation: 'Mars casts special full aspects on the 4th and 8th houses from its placement.',
    },
    {
      id: 'q11',
      questionNumber: 11,
      topic: 'Planets & Houses',
      question: 'Which planet casts full divine trinal aspects on the 5th and 9th houses from its placement?',
      options: [
        'Saturn (Shani)',
        'Jupiter (Guru)',
        'Venus (Shukra)',
        'Mercury (Budha)',
      ],
      correctOptionIndex: 1,
      explanation: 'Guru (Jupiter) casts full trinal aspects on the 5th and 9th houses from where it sits.',
    },
    {
      id: 'q12',
      questionNumber: 12,
      topic: 'Planets & Houses',
      question: 'Which planet is regarded as the Manokaraka (significator of the human mind and emotions)?',
      options: [
        'Surya (Sun)',
        'Chandra (Moon)',
        'Budha (Mercury)',
        'Guru (Jupiter)',
      ],
      correctOptionIndex: 1,
      explanation: 'The Moon (Chandra) is the significator (Karaka) for the mind, psychological state, and emotional perception.',
    },
    {
      id: 'q13',
      questionNumber: 13,
      topic: 'Birth Chart Reading',
      question: 'Approximately how often does the Ascendant (Lagna) sign change on the eastern horizon?',
      options: [
        'Every 2 hours',
        'Every 24 hours',
        'Every 2.5 days',
        'Every 30 days',
      ],
      correctOptionIndex: 0,
      explanation: 'Because the Earth rotates 360 degrees in approximately 24 hours, each of the 12 signs rises for roughly 2 hours.',
    },
    {
      id: 'q14',
      questionNumber: 14,
      topic: 'Planets & Houses',
      question: 'In which sign is Guru (Jupiter) debilitated (Neecha)?',
      options: [
        'Cancer',
        'Capricorn',
        'Gemini',
        'Virgo',
      ],
      correctOptionIndex: 1,
      explanation: 'Jupiter is exalted in Cancer and debilitated in Capricorn (Makara).',
    },
    {
      id: 'q15',
      questionNumber: 15,
      topic: 'Planets & Houses',
      question: 'Which house is primarily inspected to analyze a native\'s career, public status, and profession?',
      options: [
        '6th House',
        '7th House',
        '10th House (Karma Bhava)',
        '11th House',
      ],
      correctOptionIndex: 2,
      explanation: 'The 10th House (Karma Bhava) represents career, public standing, and accomplishments.',
    },
    {
      id: 'q16',
      questionNumber: 16,
      topic: 'Planets & Houses',
      question: 'The Trikona houses (1, 5, and 9) belong to which Purushartha (aim of life)?',
      options: [
        'Dharma (Purpose & Soul Duty)',
        'Artha (Wealth and Material Security)',
        'Kama (Desire and Relationships)',
        'Moksha (Liberation and Detachment)',
      ],
      correctOptionIndex: 0,
      explanation: 'Houses 1, 5, and 9 are the Dharma Trikonas representing spiritual merit and sacred duty.',
    },
    {
      id: 'q17',
      questionNumber: 17,
      topic: 'Planets & Houses',
      question: 'Astronomically and energetically, what are Rahu and Ketu in Vedic astrology?',
      options: [
        'Moons of Saturn',
        'The mathematical intersection nodes of the Moon’s orbital path and the Sun’s ecliptic',
        'Asteroids between Mars and Jupiter',
        'Stars in the Orion constellation',
      ],
      correctOptionIndex: 1,
      explanation: 'Rahu and Ketu are the North and South Lunar Nodes where eclipses occur.',
    },
    {
      id: 'q18',
      questionNumber: 18,
      topic: 'Planets & Houses',
      question: 'What occurs when a planet is "Combust" (Asta)?',
      options: [
        'It is in an enemy sign',
        'It is retrograding backwards',
        'It is within close degree proximity to the Sun, causing its ray visibility to be obscured',
        'It is placed in the 8th house',
      ],
      correctOptionIndex: 2,
      explanation: 'Combustion occurs when a planet comes within close degrees of the Sun.',
    },
    {
      id: 'q19',
      questionNumber: 19,
      topic: 'Ethics & Consultation',
      question: 'What is the primary ethical responsibility of a Vedic astrologer according to Acharya Niraj Kumar?',
      options: [
        'To instill fear of upcoming malefic periods',
        'To demonstrate intellectual superiority by predicting fatal events',
        'To illuminate karmic patterns compassionately, restore agency, and provide uplifting guidance',
        'To state that human free will is completely nonexistent',
      ],
      correctOptionIndex: 2,
      explanation: 'Astrology is a sacred light to restore clarity, compassionate agency, and purposeful guidance.',
    },
    {
      id: 'q20',
      questionNumber: 20,
      topic: 'Basic Predictions',
      question: 'What is the correct first step when opening any birth chart in the 5-Step Synthesis method?',
      options: [
        'Immediately look at the 8th house for crises',
        'Identify the Lagna (Ascendant), its sign, degree, and locate the placement of the Lagna Lord (Lagnesha)',
        'Check Saturn\'s transit over the Moon',
        'Check the Nakshatra of Mars',
      ],
      correctOptionIndex: 1,
      explanation: 'The foundation of all chart interpretation begins with the Lagna and the Lagna Lord.',
    },
  ],
};

/* PLACEHOLDER: Demo users */
export const DEMO_USERS: User[] = [
  {
    id: 'user-student-demo',
    name: 'Aarav Sharma',
    email: 'student@example.com',
    role: 'STUDENT',
    timezone: 'Asia/Kolkata',
    avatarUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?q=80&w=200&auto=format&fit=crop',
    enrolledCohortIds: ['cohort-wia-batch-1'],
  },
  {
    id: 'user-admin-demo',
    name: 'Acharya Niraj Kumar',
    email: 'ask@aapkaastro.com',
    role: 'OWNER',
    isOwner: true,
    timezone: 'Asia/Kolkata',
    avatarUrl: '/images/Acharya_Niraj_Kumar.jpg',
    enrolledCohortIds: ['cohort-wia-batch-1'],
  },
  {
    id: 'user-staff-content',
    name: 'Priya Verma (Staff - Courses & Quizzes)',
    email: 'priya.staff@viar.in',
    role: 'ADMIN',
    isOwner: false,
    staffSections: ['courses', 'quizzes'],
    timezone: 'Asia/Kolkata',
    avatarUrl: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?q=80&w=200&auto=format&fit=crop',
    enrolledCohortIds: [],
  },
];

/* Demo certificate */
export const DEMO_CERTIFICATES: Certificate[] = [
  {
    id: 'cert-wia-9842',
    verificationCode: 'VIAR-2026-WIA-9842',
    studentId: 'user-student-demo',
    studentName: 'Aarav Sharma',
    studentEmail: 'student@example.com',
    courseId: 'course-what-is-astrology',
    courseTitle: 'What is Astrology — Foundations of Vedic Astrology',
    cohortBatchName: 'Self-Paced Masterclass — Vihangam Institute of Astrology and Research',
    issueDate: 'October 15, 2026',
    scorePercentage: 90,
    grade: 'Distinction',
    instructorName: 'Acharya Niraj Kumar',
    instructorTitle: 'Jyotish Acharya (Bharatiya Vidya Bhavan) | Founder, VIAR & Aapaka Astro',
    verificationUrl: 'https://viar.in/verify/VIAR-2026-WIA-9842',
  },
];

/* PLACEHOLDER: Demo enrollments */
export const DEMO_ENROLLMENTS: Enrollment[] = [
  {
    id: 'enr-101',
    studentId: 'user-student-demo',
    studentName: 'Aarav Sharma',
    studentEmail: 'student@example.com',
    courseId: 'course-what-is-astrology',
    cohortId: 'cohort-wia-batch-1',
    enrolledAt: '2026-09-20T10:30:00.000Z',
    paymentStatus: 'PAID',
    paymentAmount: 4999,
    currency: 'INR',
    paymentMethod: 'UPI / Razorpay',
    paymentId: 'pay_Nz9KqP03948Viar',
  },
  {
    id: 'enr-102',
    studentId: 'user-sarah-jenkins',
    studentName: 'Sarah Jenkins',
    studentEmail: 'sarah.j@london.co.uk',
    courseId: 'course-what-is-astrology',
    cohortId: 'cohort-wia-batch-1',
    enrolledAt: '2026-09-20T14:15:00.000Z',
    paymentStatus: 'PAID',
    paymentAmount: 69,
    currency: 'USD',
    paymentMethod: 'International Card / Stripe',
    paymentId: 'ch_3M48KqP03948Stripe',
  },
  {
    id: 'enr-103',
    studentId: 'user-david-miller',
    studentName: 'David K. Miller',
    studentEmail: 'david.miller@california.com',
    courseId: 'course-what-is-astrology',
    cohortId: 'cohort-wia-batch-1',
    enrolledAt: '2026-09-21T02:40:00.000Z',
    paymentStatus: 'PAID',
    paymentAmount: 69,
    currency: 'USD',
    paymentMethod: 'Razorpay Global Card',
    paymentId: 'pay_90ViarGlobal',
  },
];
