import { Course, Cohort, ScheduledClass, FinalTest, User, Certificate, Enrollment } from './types';

export const INITIAL_COURSES: Course[] = [
  {
    id: 'course-what-is-astrology',
    slug: 'what-is-astrology',
    title: 'What is Astrology: The Complete Foundational Immersion',
    tagline: 'Learn the sacred science of Jyotish from first principles to real chart readings.',
    subtitle: '18 Live Masterclasses • 9-Week Live Cohort • Class Recordings • Final Certification Exam',
    description: 'A transformative 9-week cohort designed to take you from total curiosity to fluent chart reading. Built upon authentic Vedic Jyotish principles combined with modern psychological insight, this flagship course strips away superstition to reveal the profound mathematics, cosmic archetypes, and karmic patterns encoded in the birth chart.',
    level: 'Beginner',
    durationWeeks: 9,
    totalClasses: 18,
    classesPerWeek: 2,
    priceInr: 14999,
    priceUsd: 199,
    originalPriceInr: 24999,
    originalPriceUsd: 299,
    isPublished: true,
    featured: true,
    badge: 'Flagship Cohort',
    instructor: {
      name: 'Acharya Dr. Hemant Vashishta',
      title: 'Founder, Aapka Astro & Master Astrologer',
      bio: 'Renowned Vedic astrologer with over 22 years of clinical chart analysis and pedagogical experience. Having advised over 35,000+ individuals worldwide through Aapka Astro (aapkaastro.com), Acharya Dr. Hemant synthesizes classical Parashari Jyotish with clear, practical guidance free of fatalism.',
      experienceYears: 22,
      studentsTaught: 4800,
      avatarUrl: 'https://images.unsplash.com/photo-1544717305-2782549b5136?q=80&w=400&auto=format&fit=crop',
      aapkaAstroUrl: 'https://aapkaastro.com',
    },
    highlights: [
      '18 Live interactive classes (2 per week, 90 mins each) held via Zoom',
      'High-definition video recordings and study handouts after every class',
      'Attend live or watch recordings — both count equally toward course completion',
      'Timezone-aware scheduling: class links convert automatically to your local time',
      'Rigorous final certification test with verified, tamper-proof credential',
      'Direct access to Acharya Dr. Hemant for Q&A and practical chart workshops',
    ],
    prerequisites: [
      'No prior astrological knowledge required — starts from scratch',
      'An open mind, curiosity for celestial geometry, and basic computer/phone access',
      'Birth details (date, exact time, and location) of yourself or loved ones for practical exercises',
    ],
    whatYouWillLearn: [
      'The sacred cosmology of Vedic Jyotish vs Western Tropical astronomy',
      'The 12 Rashis (Zodiac signs): elements, modalities, and archetypal psychology',
      'The 9 Grahas (Planets): functional benefics, malefics, combustions, and dignity',
      'The 12 Bhavas (Houses): Kendra, Trikona, Dusthana, and life domains',
      'How to read a North & South Indian Kundali (birth chart) with confidence',
      'Panchanga fundamentals: Tithi, Nakshatra, Yoga, Karana, and Vara',
      'Introduction to Mahadashas and Gochara (planetary transits)',
      'Ethical guidelines: How to provide compassionate, empowering readings',
    ],
    modules: [
      {
        id: 'mod-1',
        moduleNumber: 1,
        title: 'Celestial Foundations & Cosmic Geometry',
        description: 'Understand the astronomical architecture behind Vedic astrology, the zodiac belt, and the philosophy of Karma.',
        classCount: 4,
        classNumbers: [1, 2, 3, 4],
      },
      {
        id: 'mod-2',
        moduleNumber: 2,
        title: 'The 12 Signs (Rashis) & Elemental Forces',
        description: 'Deep dive into Aries through Pisces, their ruling energies, bodily correlations, and psychological expressions.',
        classCount: 4,
        classNumbers: [5, 6, 7, 8],
      },
      {
        id: 'mod-3',
        moduleNumber: 3,
        title: 'The 9 Grahas: Cosmic Archetypes & Dignities',
        description: 'Master Sun through Ketu, planetary friendships, exaltation, debilitation, combustions, and aspects (Drishti).',
        classCount: 4,
        classNumbers: [9, 10, 11, 12],
      },
      {
        id: 'mod-4',
        moduleNumber: 4,
        title: 'The 12 Bhavas: The Theatres of Human Life',
        description: 'Decoding the 12 houses of destiny — career, relationships, health, wealth, spirituality, and past karmas.',
        classCount: 3,
        classNumbers: [13, 14, 15],
      },
      {
        id: 'mod-5',
        moduleNumber: 5,
        title: 'Synthesis, Real Kundali Reading & Timing of Events',
        description: 'Putting it all together: Step-by-step framework to analyze any birth chart, foundational transit analysis, and test prep.',
        classCount: 3,
        classNumbers: [16, 17, 18],
      },
    ],
    faqs: [
      {
        question: 'What if I cannot attend a live class due to work or timezone differences?',
        answer: 'Every single live session is recorded in HD and published to your student portal within 3 hours alongside slide decks and study notes. Watching the recording counts equally toward your learning — there is zero attendance requirement. Your certificate is unlocked by passing the final test.',
      },
      {
        question: 'How do live class links work with international timezones?',
        answer: 'Classes are scheduled and automatically rendered in your local timezone on your student dashboard. You will also receive 1-click Google Calendar / iCal download links and a direct Zoom / Google Meet join button that lights up 15 minutes before showtime.',
      },
      {
        question: 'How does the final test and certificate work?',
        answer: 'Upon completion of the 18 classes, the Final Certification Exam unlocks on your dashboard. It consists of 20 multiple-choice questions assessing practical chart understanding. Scoring 70% or higher generates a verifiable digital certificate with a unique verification code that can be shared on LinkedIn or verified at viar.in/verify.',
      },
      {
        question: 'Is this affiliated with Aapka Astro?',
        answer: 'Yes! Viar.in is the dedicated educational academy founded by the same master astrologer behind Aapka Astro (aapkaastro.com). While Aapka Astro provides 1-on-1 private client consultations, Viar.in is where Acharya Dr. Hemant trains aspiring astrologers, enthusiasts, and practitioners.',
      },
      {
        question: 'Is the payment one-time or recurring?',
        answer: 'It is strictly a one-time enrollment payment with lifetime access to the 18 class recordings, slide decks, and your certification. No hidden fees or recurring subscriptions.',
      },
    ],
  },
  {
    id: 'course-predictive-dashas',
    slug: 'predictive-astrology-dashas-transits',
    title: 'Predictive Astrology: Vimshottari Dasha & Planetary Transits',
    tagline: 'Master the clockwork of destiny and accurately pinpoint timing of events.',
    subtitle: '16 Live Masterclasses • 8-Week Cohort • Advanced Timing Methods',
    description: 'Learn how to accurately determine WHEN events will unfold. This intermediate cohort dives into the 120-year Vimshottari Dasha cycle, Antardashas, Pratyantardashas, and their dynamic interaction with Gochara (transits of Jupiter, Saturn, and Rahu/Ketu).',
    level: 'Intermediate',
    durationWeeks: 8,
    totalClasses: 16,
    classesPerWeek: 2,
    priceInr: 18999,
    priceUsd: 249,
    originalPriceInr: 29999,
    originalPriceUsd: 349,
    isPublished: true,
    featured: false,
    badge: 'Next Batch Enrolling',
    instructor: {
      name: 'Acharya Dr. Hemant Vashishta',
      title: 'Founder, Aapka Astro & Master Astrologer',
      bio: 'Renowned Vedic astrologer with over 22 years of clinical chart analysis and pedagogical experience.',
      experienceYears: 22,
      studentsTaught: 4800,
      avatarUrl: 'https://images.unsplash.com/photo-1544717305-2782549b5136?q=80&w=400&auto=format&fit=crop',
      aapkaAstroUrl: 'https://aapkaastro.com',
    },
    highlights: [
      '16 Live intensive masterclasses with live chart examples',
      'Master the 120-year Vimshottari Dasha system down to sub-periods',
      'Jupiter and Saturn double-transit rule for major life milestones',
      'Sade Sati and Kantaka Shani real-world mitigation & timing',
    ],
    prerequisites: [
      'Completion of "What is Astrology" or equivalent knowledge of Rashis, Grahas, and Bhavas',
    ],
    whatYouWillLearn: [
      'Calculation and interpretation of Vimshottari Dasha, Bhukti, and Antara',
      'Predicting career promotions, job shifts, and financial surges',
      'Timing marriage, relationships, and child birth',
      'Health vulnerability periods and transit triggers',
    ],
    modules: [
      {
        id: 'mod-dasha-1',
        moduleNumber: 1,
        title: 'The Dasha Engine & Nakshatra Lords',
        description: 'Mechanism of Dasha calculations based on the natal Moon position.',
        classCount: 4,
        classNumbers: [1, 2, 3, 4],
      },
      {
        id: 'mod-dasha-2',
        moduleNumber: 2,
        title: 'Synthesizing Dasha with Planetary Transits (Gochara)',
        description: 'How static natal promises are unlocked by dynamic celestial clocks.',
        classCount: 6,
        classNumbers: [5, 6, 7, 8, 9, 10],
      },
      {
        id: 'mod-dasha-3',
        moduleNumber: 3,
        title: 'Applied Predictions & Case Studies',
        description: 'Deep clinical chart analysis across 50+ real anonymized native charts.',
        classCount: 6,
        classNumbers: [11, 12, 13, 14, 15, 16],
      },
    ],
    faqs: [
      {
        question: 'Can I take this course without completing What is Astrology?',
        answer: 'You must have a solid foundation in the 12 signs, 9 planets, and 12 houses. If you are a beginner, we strongly advise starting with "What is Astrology" first.',
      },
    ],
  },
];

export const INITIAL_COHORTS: Cohort[] = [
  {
    id: 'cohort-wia-batch-1',
    courseId: 'course-what-is-astrology',
    batchNumber: 1,
    batchName: 'Autumn 2026 Batch (Cohort 01)',
    startDate: '2026-10-03T14:30:00.000Z', // Saturday Oct 3, 2026, 8:00 PM IST (14:30 UTC)
    endDate: '2026-12-06T16:00:00.000Z',
    scheduleDescription: 'Every Saturday & Sunday at 8:00 PM – 9:30 PM IST (converts to your local time)',
    scheduleTimeUtc: {
      dayOfWeek: [6, 0], // Saturday and Sunday
      hoursUtc: 14,
      minutesUtc: 30,
    },
    maxSeats: 60,
    enrolledCount: 42,
    status: 'ENROLLING',
    enrollmentDeadline: '2026-10-02T23:59:59.000Z',
  },
  {
    id: 'cohort-dashas-batch-1',
    courseId: 'course-predictive-dashas',
    batchNumber: 1,
    batchName: 'Winter 2026 Master Batch',
    startDate: '2026-11-07T14:30:00.000Z',
    endDate: '2027-01-03T16:00:00.000Z',
    scheduleDescription: 'Every Saturday & Sunday at 5:30 PM – 7:00 PM IST',
    scheduleTimeUtc: {
      dayOfWeek: [6, 0],
      hoursUtc: 12,
      minutesUtc: 0,
    },
    maxSeats: 40,
    enrolledCount: 18,
    status: 'ENROLLING',
    enrollmentDeadline: '2026-11-06T23:59:59.000Z',
  },
];

export const SCHEDULED_CLASSES_FLAGSHIP: ScheduledClass[] = [
  {
    id: 'cls-1',
    cohortId: 'cohort-wia-batch-1',
    classNumber: 1,
    moduleNumber: 1,
    title: 'Orientation, Cosmic Philosophy & The Karma Model',
    subtitle: 'Introduction to Jyotish as the Eye of the Vedas',
    description: 'The difference between fate, free will, and astrological probability. Understanding the celestial sphere, ecliptic plane, and why Jyotish is a science of light and time.',
    scheduledStartTime: '2026-10-03T14:30:00.000Z',
    durationMinutes: 90,
    meetingPlatform: 'ZOOM',
    joinUrl: 'https://zoom.us/j/98142385102?pwd=VIAR_ASTROLOGY_CLASS_01',
    meetingId: '981 4238 5102',
    passcode: 'VIAR2026',
    status: 'COMPLETED',
    recording: {
      id: 'rec-1',
      videoUrl: 'https://www.youtube.com/embed/dQw4w9WgXcQ', // Embedded demo video
      provider: 'YOUTUBE',
      durationMinutes: 92,
      recordedDate: '2026-10-03',
      notesMarkdown: `### Class 1 Summary & Key Formulas\n\n1. **Jyotish Definition**: 'Jyoti' (Light) + 'Isha' (Divine Lord) = The divine science that illuminates the path of the soul.\n2. **The 3 Types of Karma**:\n   - *Sanchita*: The total reservoir of accumulated karmas.\n   - *Prarabdha*: The slice of karma ripe for fruition in this current incarnation (mapped precisely by the natal chart).\n   - *Kriyamana*: Current action and free will exercised right now.\n3. **Sidereal vs. Tropical Zodiac**: Jyotish relies on the Sidereal (Nirayana) zodiac which accounts for the Precession of the Equinoxes (Ayanamsha).`,
      keyTakeaways: [
        'Astrology is an indicator of karmic weather, not a deterministic prison',
        'Sidereal zodiac aligns with actual astronomical constellations',
        'Your birth chart is the blueprint of Prarabdha Karma',
      ],
      resources: [
        {
          id: 'res-1-1',
          title: 'Class 01 Slide Deck - Foundations of Jyotish.pdf',
          type: 'PDF',
          url: '/resources/class1-slides.pdf',
          size: '4.2 MB',
        },
        {
          id: 'res-1-2',
          title: 'Ayanamsha Comparison Cheatsheet.pdf',
          type: 'PDF',
          url: '/resources/ayanamsha-cheatsheet.pdf',
          size: '1.1 MB',
        },
      ],
    },
  },
  {
    id: 'cls-2',
    cohortId: 'cohort-wia-batch-1',
    classNumber: 2,
    moduleNumber: 1,
    title: 'The Great Zodiac Belt & Chart Formats',
    subtitle: 'North Indian vs South Indian Kundali layouts',
    description: 'Deciphering the 360-degree zodiac ring divided into 12 signs of 30 degrees each. How to read and construct both North Indian (diamond) and South Indian (box) birth charts with complete ease.',
    scheduledStartTime: '2026-10-04T14:30:00.000Z',
    durationMinutes: 90,
    meetingPlatform: 'ZOOM',
    joinUrl: 'https://zoom.us/j/98142385102?pwd=VIAR_ASTROLOGY_CLASS_02',
    meetingId: '981 4238 5102',
    passcode: 'VIAR2026',
    status: 'COMPLETED',
    recording: {
      id: 'rec-2',
      videoUrl: 'https://www.youtube.com/embed/dQw4w9WgXcQ',
      provider: 'YOUTUBE',
      durationMinutes: 89,
      recordedDate: '2026-10-04',
      notesMarkdown: `### Reading North vs South Indian Charts\n\n- **North Indian Style**:\n  - Houses are permanently fixed.\n  - The top center diamond is always House 1 (Lagna / Ascendant).\n  - Numbers written inside the boxes indicate the Rashi (Sign), NOT the house number.\n- **South Indian Style**:\n  - Signs are permanently fixed in clockwise order starting with Aries in the second box of the top row.\n  - An oblique diagonal slash denotes the Lagna.`,
      keyTakeaways: [
        'North Indian charts have fixed houses; numbers represent signs',
        'South Indian charts have fixed signs; marker shows the ascendant',
        'Mastering both styles gives you versatility across all classical texts',
      ],
      resources: [
        {
          id: 'res-2-1',
          title: 'Blank Kundali Practice Templates (North & South).pdf',
          type: 'PDF',
          url: '/resources/kundali-templates.pdf',
          size: '850 KB',
        },
      ],
    },
  },
  {
    id: 'cls-3',
    cohortId: 'cohort-wia-batch-1',
    classNumber: 3,
    moduleNumber: 1,
    title: 'Panchanga: The 5 Limbs of Time',
    subtitle: 'Tithi, Vara, Nakshatra, Yoga, and Karana',
    description: 'How every moment in spacetime is governed by the dynamic dance between the Sun (soul) and the Moon (mind). Calculating and interpreting the five vital pillars of the Vedic calendar.',
    scheduledStartTime: '2026-10-10T14:30:00.000Z',
    durationMinutes: 90,
    meetingPlatform: 'ZOOM',
    joinUrl: 'https://zoom.us/j/98142385102?pwd=VIAR_ASTROLOGY_CLASS_03',
    meetingId: '981 4238 5102',
    passcode: 'VIAR2026',
    status: 'COMPLETED',
    recording: {
      id: 'rec-3',
      videoUrl: 'https://www.youtube.com/embed/dQw4w9WgXcQ',
      provider: 'YOUTUBE',
      durationMinutes: 94,
      recordedDate: '2026-10-10',
      notesMarkdown: `### The Five Elements of Panchanga\n\n1. **Vara** (Fire element): Day of the week ruled by the 7 classical planets (Sun to Saturn).\n2. **Tithi** (Water element): Lunar day calculated by the 12-degree separation between Sun and Moon.\n3. **Nakshatra** (Air element): Lunar mansion occupied by the Moon (27 total mansions).\n4. **Yoga** (Ether element): Addition of solar and lunar longitudes.\n5. **Karana** (Earth element): Half of a Tithi (60 Karanas in a lunar month).`,
      keyTakeaways: [
        'Panchanga defines the energetic quality and auspiciousness of time',
        'Your birth Tithi reflects emotional harmony and relationship karma',
        'The birth Nakshatra determines your primary emotional lens on reality',
      ],
      resources: [
        {
          id: 'res-3-1',
          title: 'Complete 30 Tithis and Their Deities Reference.pdf',
          type: 'PDF',
          url: '/resources/tithi-reference.pdf',
          size: '1.8 MB',
        },
      ],
    },
  },
  {
    id: 'cls-4',
    cohortId: 'cohort-wia-batch-1',
    classNumber: 4,
    moduleNumber: 1,
    title: 'The Ascendant (Lagna) & Birth Moment Calculation',
    subtitle: 'The Horizon, Eastern Sky, and the Physical Incarnation',
    description: 'Why the exact time of birth is paramount in Vedic astrology. The Lagna changes every ~2 hours and sets the entire blueprint for all 12 houses of human existence.',
    scheduledStartTime: '2026-10-11T14:30:00.000Z',
    durationMinutes: 90,
    meetingPlatform: 'ZOOM',
    joinUrl: 'https://zoom.us/j/98142385102?pwd=VIAR_ASTROLOGY_CLASS_04',
    meetingId: '981 4238 5102',
    passcode: 'VIAR2026',
    status: 'COMPLETED',
    recording: {
      id: 'rec-4',
      videoUrl: 'https://www.youtube.com/embed/dQw4w9WgXcQ',
      provider: 'YOUTUBE',
      durationMinutes: 91,
      recordedDate: '2026-10-11',
      notesMarkdown: `### The Importance of Lagna\n\n- The Lagna is the rising sign on the eastern horizon at the precise second of birth.\n- It represents the physical body, vitality, character, and worldly orientation.\n- Even twins born 10 minutes apart can have different Lagnas or Navamsha divisions.`,
      keyTakeaways: [
        'Lagna is the primary focal point of the entire chart',
        'Exact birth time accuracy is essential for precise analysis',
      ],
      resources: [
        {
          id: 'res-4-1',
          title: 'Birth Time Rectification Guidelines.pdf',
          type: 'PDF',
          url: '/resources/rectification.pdf',
          size: '950 KB',
        },
      ],
    },
  },
  {
    id: 'cls-5',
    cohortId: 'cohort-wia-batch-1',
    classNumber: 5,
    moduleNumber: 2,
    title: 'The 4 Elements & 3 Gunas of the Zodiac',
    subtitle: 'Fire, Earth, Air, Water & Chara, Sthira, Dwiswabhava',
    description: 'Classifying the 12 signs through the lens of elemental forces (Agni, Prithvi, Vayu, Jala) and modes of motion (Movable, Fixed, Dual). How this forms the psychological foundation of character.',
    scheduledStartTime: '2026-10-17T14:30:00.000Z',
    durationMinutes: 90,
    meetingPlatform: 'ZOOM',
    joinUrl: 'https://zoom.us/j/98142385102?pwd=VIAR_ASTROLOGY_CLASS_05',
    meetingId: '981 4238 5102',
    passcode: 'VIAR2026',
    status: 'COMPLETED',
    recording: {
      id: 'rec-5',
      videoUrl: 'https://www.youtube.com/embed/dQw4w9WgXcQ',
      provider: 'YOUTUBE',
      durationMinutes: 88,
      recordedDate: '2026-10-17',
      notesMarkdown: `### Elemental Architecture\n\n- **Fire Signs (1, 5, 9)**: Aries, Leo, Sagittarius — Dharma, inspiration, enthusiasm.\n- **Earth Signs (2, 6, 10)**: Taurus, Virgo, Capricorn — Artha, stability, resourcefulness.\n- **Air Signs (3, 7, 11)**: Gemini, Libra, Aquarius — Kama, intellect, communication.\n- **Water Signs (4, 8, 12)**: Cancer, Scorpio, Pisces — Moksha, emotion, intuition.`,
      keyTakeaways: [
        'Four elements map directly to the four Purusharthas (aims of human life)',
        'Sign modality reveals how energy is initiated, sustained, or adapted',
      ],
      resources: [
        {
          id: 'res-5-1',
          title: 'Elemental Balance Diagnostic Chart.pdf',
          type: 'PDF',
          url: '/resources/elemental-balance.pdf',
          size: '1.2 MB',
        },
      ],
    },
  },
  {
    id: 'cls-6',
    cohortId: 'cohort-wia-batch-1',
    classNumber: 6,
    moduleNumber: 2,
    title: 'The Signs Part 1: Aries through Cancer',
    subtitle: 'The Archetypes of Inception, Nourishment & Rooting',
    description: 'Deep analytical breakdown of Mesha (Aries), Vrishabha (Taurus), Mithuna (Gemini), and Karka (Cancer). Symbolism, ruling grahas, body parts, strengths, and shadow patterns.',
    scheduledStartTime: '2026-10-18T14:30:00.000Z',
    durationMinutes: 90,
    meetingPlatform: 'ZOOM',
    joinUrl: 'https://zoom.us/j/98142385102?pwd=VIAR_ASTROLOGY_CLASS_06',
    meetingId: '981 4238 5102',
    passcode: 'VIAR2026',
    status: 'COMPLETED',
    recording: {
      id: 'rec-6',
      videoUrl: 'https://www.youtube.com/embed/dQw4w9WgXcQ',
      provider: 'YOUTUBE',
      durationMinutes: 95,
      recordedDate: '2026-10-18',
      notesMarkdown: `### First Quadrant Signs Breakdown\n\n1. **Aries (Mesha)**: Cardinal Fire | Ruled by Mars | Head & Vitality | Pioneering initiator.\n2. **Taurus (Vrishabha)**: Fixed Earth | Ruled by Venus | Throat & Assets | Preserver of value.\n3. **Gemini (Mithuna)**: Dual Air | Ruled by Mercury | Shoulders & Hands | Networking communicator.\n4. **Cancer (Karka)**: Cardinal Water | Ruled by Moon | Chest & Emotions | Nurturing protector.`,
      keyTakeaways: [
        'Signs 1-4 govern the personal, foundational stage of individual consciousness',
        'Observe how the ruler colours every house that sign falls into',
      ],
      resources: [],
    },
  },
  {
    id: 'cls-7',
    cohortId: 'cohort-wia-batch-1',
    classNumber: 7,
    moduleNumber: 2,
    title: 'The Signs Part 2: Leo through Scorpio',
    subtitle: 'The Archetypes of Sovereign Expression, Discernment & Metamorphosis',
    description: 'Exploring Simha (Leo), Kanya (Virgo), Tula (Libra), and Vrischika (Scorpio). Understanding public expression, service, relational equilibrium, and deep psychological crisis & regeneration.',
    scheduledStartTime: '2026-10-24T14:30:00.000Z',
    durationMinutes: 90,
    meetingPlatform: 'ZOOM',
    joinUrl: 'https://zoom.us/j/98142385102?pwd=VIAR_ASTROLOGY_CLASS_07',
    meetingId: '981 4238 5102',
    passcode: 'VIAR2026',
    status: 'COMPLETED',
    recording: {
      id: 'rec-7',
      videoUrl: 'https://www.youtube.com/embed/dQw4w9WgXcQ',
      provider: 'YOUTUBE',
      durationMinutes: 91,
      recordedDate: '2026-10-24',
      notesMarkdown: `### Second Quadrant Signs Breakdown\n\n- **Leo (Simha)**: Fixed Fire | Sun | Heart & Leadership | Creative sovereignty.\n- **Virgo (Kanya)**: Dual Earth | Mercury | Digestive System | Precision, healing, service.\n- **Libra (Tula)**: Cardinal Air | Venus | Kidneys & Balance | Social harmony, contracts.\n- **Scorpio (Vrischika)**: Fixed Water | Mars (Ketu co-rule) | Pelvis & Secrets | Kundalini transformation.`,
      keyTakeaways: [
        'Signs 5-8 shift from self to relationship and society',
        'Scorpio represents the inevitable ego death required for spiritual awakening',
      ],
      resources: [],
    },
  },
  {
    id: 'cls-8',
    cohortId: 'cohort-wia-batch-1',
    classNumber: 8,
    moduleNumber: 2,
    title: 'The Signs Part 3: Sagittarius through Pisces',
    subtitle: 'The Higher Wisdom, Mastery & Cosmic Dissolution',
    description: 'Analyzing Dhanu (Sagittarius), Makara (Capricorn), Kumbha (Aquarius), and Meena (Pisces). Philosophical seeking, institutional karma, universal humanity, and the ultimate return to the source.',
    scheduledStartTime: '2026-10-25T14:30:00.000Z',
    durationMinutes: 90,
    meetingPlatform: 'ZOOM',
    joinUrl: 'https://zoom.us/j/98142385102?pwd=VIAR_ASTROLOGY_CLASS_08',
    meetingId: '981 4238 5102',
    passcode: 'VIAR2026',
    status: 'COMPLETED',
    recording: {
      id: 'rec-8',
      videoUrl: 'https://www.youtube.com/embed/dQw4w9WgXcQ',
      provider: 'YOUTUBE',
      durationMinutes: 93,
      recordedDate: '2026-10-25',
      notesMarkdown: `### Third Quadrant Signs Breakdown\n\n- **Sagittarius (Dhanu)**: Dual Fire | Jupiter | Thighs | Higher dharma, guru, expansion.\n- **Capricorn (Makara)**: Cardinal Earth | Saturn | Knees | Discipline, societal duty, endurance.\n- **Aquarius (Kumbha)**: Fixed Air | Saturn (Rahu co-rule) | Calves | Innovations, collective consciousness.\n- **Pisces (Meena)**: Dual Water | Jupiter | Feet | Surrender, transcendence, dream states.`,
      keyTakeaways: [
        'Signs 9-12 represent the transpersonal, universal stages of existence',
        'Pisces marks the culmination of the 360-degree journey before the cycle repeats',
      ],
      resources: [],
    },
  },
  {
    id: 'cls-9',
    cohortId: 'cohort-wia-batch-1',
    classNumber: 9,
    moduleNumber: 3,
    title: 'The Luminaries: Surya (Sun) & Chandra (Moon)',
    subtitle: 'The Soul & Mind: Atmakaraka and Manokaraka',
    description: 'The two lights of the cosmos. Surya as the divine spark, father, vitality, and authority; Chandra as perception, emotion, mother, and mental serenity.',
    scheduledStartTime: '2026-10-31T14:30:00.000Z',
    durationMinutes: 90,
    meetingPlatform: 'ZOOM',
    joinUrl: 'https://zoom.us/j/98142385102?pwd=VIAR_ASTROLOGY_CLASS_09',
    meetingId: '981 4238 5102',
    passcode: 'VIAR2026',
    status: 'COMPLETED',
    recording: {
      id: 'rec-9',
      videoUrl: 'https://www.youtube.com/embed/dQw4w9WgXcQ',
      provider: 'YOUTUBE',
      durationMinutes: 96,
      recordedDate: '2026-10-31',
      notesMarkdown: `### Sun and Moon in Depth\n\n- **Surya**: Natural Karaka for the Soul, Father, Government, Royalty, Bone structure.\n- **Chandra**: Natural Karaka for Mind, Mother, Liquids, Public approval, Emotional equilibrium.\n- A strong Moon shields the native from heavy planetary afflictions; an afflicted Moon causes anxiety.`,
      keyTakeaways: [
        'Sun gives the core essence and pride; Moon determines how life is felt and processed',
        'Exaltation of Sun is Aries (10°); Moon is Taurus (3°)',
      ],
      resources: [],
    },
  },
  {
    id: 'cls-10',
    cohortId: 'cohort-wia-batch-1',
    classNumber: 10,
    moduleNumber: 3,
    title: 'Mangala (Mars) & Budha (Mercury)',
    subtitle: 'Courage, Willpower & Analytical Intellect',
    description: 'Mangala as the warrior, land, siblings, and drive to act. Budha as discrimination (Viveka), speech, commerce, logic, and humour. How their interaction shapes decisions.',
    scheduledStartTime: '2026-11-01T14:30:00.000Z',
    durationMinutes: 90,
    meetingPlatform: 'ZOOM',
    joinUrl: 'https://zoom.us/j/98142385102?pwd=VIAR_ASTROLOGY_CLASS_10',
    meetingId: '981 4238 5102',
    passcode: 'VIAR2026',
    status: 'COMPLETED',
    recording: {
      id: 'rec-10',
      videoUrl: 'https://www.youtube.com/embed/dQw4w9WgXcQ',
      provider: 'YOUTUBE',
      durationMinutes: 89,
      recordedDate: '2026-11-01',
      notesMarkdown: `### Mars and Mercury Dynamics\n\n- **Mars**: Ruler of Aries & Scorpio. Exalted in Capricorn (28°), Debilitated in Cancer (28°).\n- **Mercury**: Ruler of Gemini & Virgo. Exalted in Virgo (15°), Debilitated in Pisces (15°).\n- Mars is action; Mercury is calculation. When in harmony, brilliant strategic leadership results.`,
      keyTakeaways: [
        'Mars directs energy outward; without Mercury it acts rashly',
        'Mercury adapts to whoever it associates with in the chart',
      ],
      resources: [],
    },
  },
  {
    id: 'cls-11',
    cohortId: 'cohort-wia-batch-1',
    classNumber: 11,
    moduleNumber: 3,
    title: 'Guru (Jupiter) & Shukra (Venus)',
    subtitle: 'The Great Benefics: Divine Grace & Material Refinement',
    description: 'Guru (Brihaspati) as dharma, children, wisdom, and fortune. Shukra (Shukracharya) as love, aesthetics, vehicles, healing, and devotion. Exploring the difference between the two teachers.',
    scheduledStartTime: '2026-11-07T14:30:00.000Z',
    durationMinutes: 90,
    meetingPlatform: 'GOOGLE_MEET',
    joinUrl: 'https://meet.google.com/xyz-viar-demo',
    meetingId: 'xyz-viar-demo',
    passcode: 'GURU2026',
    status: 'LIVE', // Simulated upcoming or currently live class!
  },
  {
    id: 'cls-12',
    cohortId: 'cohort-wia-batch-1',
    classNumber: 12,
    moduleNumber: 3,
    title: 'Shani (Saturn) & The Nodes (Rahu & Ketu)',
    subtitle: 'The Great Taskmaster & The Karmic Axis',
    description: 'Shani as patience, longevity, sorrow, hard work, and justice. Rahu as obsession, foreign matters, and future karma; Ketu as detachment, spiritual liberation, and past-life mastery.',
    scheduledStartTime: '2026-11-08T14:30:00.000Z',
    durationMinutes: 90,
    meetingPlatform: 'ZOOM',
    joinUrl: 'https://zoom.us/j/98142385102?pwd=VIAR_ASTROLOGY_CLASS_12',
    meetingId: '981 4238 5102',
    passcode: 'VIAR2026',
    status: 'UPCOMING',
  },
  {
    id: 'cls-13',
    cohortId: 'cohort-wia-batch-1',
    classNumber: 13,
    moduleNumber: 4,
    title: 'Bhavas 1 to 4: The Internal Foundation',
    subtitle: 'Self, Wealth, Valour & Inner Happiness',
    description: 'House 1 (Tanu Bhava), House 2 (Dhana Bhava), House 3 (Sahaja Bhava), and House 4 (Sukha Bhava). Assessing physical vitality, family wealth, courage, mother, and land.',
    scheduledStartTime: '2026-11-14T14:30:00.000Z',
    durationMinutes: 90,
    meetingPlatform: 'ZOOM',
    joinUrl: 'https://zoom.us/j/98142385102?pwd=VIAR_ASTROLOGY_CLASS_13',
    meetingId: '981 4238 5102',
    passcode: 'VIAR2026',
    status: 'UPCOMING',
  },
  {
    id: 'cls-14',
    cohortId: 'cohort-wia-batch-1',
    classNumber: 14,
    moduleNumber: 4,
    title: 'Bhavas 5 to 8: Creative Expression & Crises',
    subtitle: 'Intelligence, Enemies, Marriage & Transformation',
    description: 'House 5 (Putra Bhava), House 6 (Ari/Ripu Bhava), House 7 (Yuvati/Kalatra Bhava), and House 8 (Randhra Bhava). Deciphering children, intellect, debts, disease, partnerships, and hidden secrets.',
    scheduledStartTime: '2026-11-15T14:30:00.000Z',
    durationMinutes: 90,
    meetingPlatform: 'ZOOM',
    joinUrl: 'https://zoom.us/j/98142385102?pwd=VIAR_ASTROLOGY_CLASS_14',
    meetingId: '981 4238 5102',
    passcode: 'VIAR2026',
    status: 'UPCOMING',
  },
  {
    id: 'cls-15',
    cohortId: 'cohort-wia-batch-1',
    classNumber: 15,
    moduleNumber: 4,
    title: 'Bhavas 9 to 12: Destiny, Career, Gains & Liberation',
    subtitle: 'Fortune, Status, Desires & Transcendence',
    description: 'House 9 (Dharma/Bhagya), House 10 (Karma Bhava), House 11 (Labha Bhava), and House 12 (Vyaya/Moksha). The peak of worldly achievement and spiritual expenditure.',
    scheduledStartTime: '2026-11-21T14:30:00.000Z',
    durationMinutes: 90,
    meetingPlatform: 'ZOOM',
    joinUrl: 'https://zoom.us/j/98142385102?pwd=VIAR_ASTROLOGY_CLASS_15',
    meetingId: '981 4238 5102',
    passcode: 'VIAR2026',
    status: 'UPCOMING',
  },
  {
    id: 'cls-16',
    cohortId: 'cohort-wia-batch-1',
    classNumber: 16,
    moduleNumber: 5,
    title: 'Planetary Aspects (Drishti) & Conjunctions (Yutis)',
    subtitle: 'How planets communicate and merge energies',
    description: 'Special aspects of Mars (4th, 8th), Jupiter (5th, 9th), and Saturn (3rd, 10th). Planetary warfare (Graha Yuddha), combustions (Asta), and combustion degree boundaries.',
    scheduledStartTime: '2026-11-22T14:30:00.000Z',
    durationMinutes: 90,
    meetingPlatform: 'ZOOM',
    joinUrl: 'https://zoom.us/j/98142385102?pwd=VIAR_ASTROLOGY_CLASS_16',
    meetingId: '981 4238 5102',
    passcode: 'VIAR2026',
    status: 'UPCOMING',
  },
  {
    id: 'cls-17',
    cohortId: 'cohort-wia-batch-1',
    classNumber: 17,
    moduleNumber: 5,
    title: 'Chart Reading Framework: The 5-Step Synthesis',
    subtitle: 'Live Chart Analysis Workshop with Real Native Charts',
    description: 'A structured, reproducible protocol to analyze any birth chart in under 15 minutes. Step 1: Lagna & Lagnesha, Step 2: Moon & Mind, Step 3: Sun & Vitality, Step 4: 10th Lord & Career, Step 5: Current Dasha.',
    scheduledStartTime: '2026-11-28T14:30:00.000Z',
    durationMinutes: 90,
    meetingPlatform: 'ZOOM',
    joinUrl: 'https://zoom.us/j/98142385102?pwd=VIAR_ASTROLOGY_CLASS_17',
    meetingId: '981 4238 5102',
    passcode: 'VIAR2026',
    status: 'UPCOMING',
  },
  {
    id: 'cls-18',
    cohortId: 'cohort-wia-batch-1',
    classNumber: 18,
    moduleNumber: 5,
    title: 'Final Synthesis, Ethical Consultation & Exam Prep',
    subtitle: 'Course Finale, Q&A with Acharya Dr. Hemant & Certification Briefing',
    description: 'Astrological ethics: Do not harm, maintain confidentiality, empower the native. Detailed review of exam topics, format, grading system, and certificate issuance procedure.',
    scheduledStartTime: '2026-11-29T14:30:00.000Z',
    durationMinutes: 90,
    meetingPlatform: 'ZOOM',
    joinUrl: 'https://zoom.us/j/98142385102?pwd=VIAR_ASTROLOGY_CLASS_18',
    meetingId: '981 4238 5102',
    passcode: 'VIAR2026',
    status: 'UPCOMING',
  },
];

export const INITIAL_FINAL_TEST: FinalTest = {
  id: 'test-wia-final',
  cohortId: 'cohort-wia-batch-1',
  courseId: 'course-what-is-astrology',
  title: 'Viar Academy: What is Astrology — Final Certification Examination',
  description: 'This comprehensive exam evaluates your conceptual, astronomical, and chart interpretation mastery across all 18 classes. You must achieve a score of 70% (14 out of 20) or higher to earn your certified credential.',
  passingPercentage: 70,
  durationMinutes: 45,
  totalQuestions: 20,
  questions: [
    {
      id: 'q1',
      questionNumber: 1,
      topic: 'Foundations',
      question: 'In Vedic Astrology (Jyotish), which zodiac system is utilized, and why?',
      options: [
        'Tropical (Sayana) zodiac, because it aligns with the seasons',
        'Sidereal (Nirayana) zodiac, because it accounts for the precession of equinoxes (Ayanamsha)',
        'Heliocentric zodiac, because the Sun is at the center of the solar system',
        'Equinoctial zodiac, because day and night are equal',
      ],
      correctOptionIndex: 1,
      explanation: 'Vedic Jyotish uses the Sidereal (Nirayana) zodiac, which incorporates Ayanamsha (precession of the equinoxes) so that the zodiac signs correspond to the actual astronomical positions of the constellations.',
    },
    {
      id: 'q2',
      questionNumber: 2,
      topic: 'Chart Layouts',
      question: 'In a North Indian diamond birth chart (Kundali), which element is permanently fixed?',
      options: [
        'The Zodiac Signs (Rashis)',
        'The Planets (Grahas)',
        'The Houses (Bhavas)',
        'The Degrees of the Ascendant',
      ],
      correctOptionIndex: 2,
      explanation: 'In the North Indian chart format, the Houses (Bhavas) are permanently fixed in position, with House 1 always situated in the top center diamond. Numbers written inside the chart indicate the Signs (Rashis), not the house numbers.',
    },
    {
      id: 'q3',
      questionNumber: 3,
      topic: 'Karmic Model',
      question: 'Which type of Karma is mapped specifically and experienced as destiny in the natal birth chart?',
      options: [
        'Sanchita Karma (the total unmanifested storehouse)',
        'Prarabdha Karma (the activated karma allotted for this lifetime)',
        'Kriyamana Karma (the current instant actions being created)',
        'Agami Karma (future planned actions)',
      ],
      correctOptionIndex: 1,
      explanation: 'Prarabdha Karma is that portion of the soul’s total accumulated karma (Sanchita) that has ripened to be experienced in the present incarnation, as mapped by the planetary positions at birth.',
    },
    {
      id: 'q4',
      questionNumber: 4,
      topic: 'Panchanga',
      question: 'A Tithi (lunar day) is calculated based on which astronomical measurement?',
      options: [
        'Each 24-hour solar day from sunrise to sunrise',
        'Each 13°20\' arc of the Moon in a Nakshatra',
        'Each 12° angular longitudinal separation between the Moon and the Sun',
        'The Moon passing through the Meridian',
      ],
      correctOptionIndex: 2,
      explanation: 'A Tithi is precisely 12 degrees of longitudinal distance between the Moon and the Sun (360° / 30 Tithis = 12° per Tithi).',
    },
    {
      id: 'q5',
      questionNumber: 5,
      topic: 'Planetary Dignity',
      question: 'In which zodiac sign and degree does Surya (the Sun) attain its highest exaltation (Paramochha)?',
      options: [
        'Leo at 1°',
        'Aries at 10°',
        'Sagittarius at 15°',
        'Capricorn at 28°',
      ],
      correctOptionIndex: 1,
      explanation: 'The Sun is exalted in Aries (Mesha), reaching its deepest point of exaltation at exactly 10 degrees of Aries.',
    },
    {
      id: 'q6',
      questionNumber: 6,
      topic: 'Houses (Bhavas)',
      question: 'Which houses are designated as the Kendra (angular/quadrant) houses in a birth chart?',
      options: [
        'Houses 1, 4, 7, and 10',
        'Houses 1, 5, and 9',
        'Houses 3, 6, 10, and 11',
        'Houses 6, 8, and 12',
      ],
      correctOptionIndex: 0,
      explanation: 'Houses 1, 4, 7, and 10 are the Kendra houses (pillars of the chart), representing Vishnu Sthana (pillars of sustenance and action).',
    },
    {
      id: 'q7',
      questionNumber: 7,
      topic: 'Houses (Bhavas)',
      question: 'Houses 6, 8, and 12 are known in Vedic astrology as:',
      options: [
        'Trikona houses (Houses of Grace)',
        'Dusthana houses (Houses of Struggle, Transformation, and Loss)',
        'Upachaya houses (Houses of Growth)',
        'Maraka houses (Death-inflicting houses)',
      ],
      correctOptionIndex: 1,
      explanation: 'Houses 6 (debts/disease), 8 (longevity/transformation/crises), and 12 (losses/moksha/foreign lands) are classified as Dusthana houses.',
    },
    {
      id: 'q8',
      questionNumber: 8,
      topic: 'Elements & Signs',
      question: 'Which of the following sets of signs belongs to the Water element (Jala Tattva)?',
      options: [
        'Taurus, Virgo, Capricorn',
        'Aries, Leo, Sagittarius',
        'Cancer, Scorpio, Pisces',
        'Gemini, Libra, Aquarius',
      ],
      correctOptionIndex: 2,
      explanation: 'Cancer (Karka), Scorpio (Vrischika), and Pisces (Meena) are the three Water (Jala) signs of the zodiac, governing emotion, intuition, and Moksha.',
    },
    {
      id: 'q9',
      questionNumber: 9,
      topic: 'Planetary Rulership',
      question: 'Which planet co-rules Scorpio (Vrischika) alongside Mars, according to classical tradition?',
      options: [
        'Rahu',
        'Ketu',
        'Saturn',
        'Jupiter',
      ],
      correctOptionIndex: 1,
      explanation: 'In classical Parashari and Jaimini Jyotish, Ketu is recognized as the co-ruler of Scorpio, reflecting Scorpio’s connection to hidden spiritual secrets and Moksha.',
    },
    {
      id: 'q10',
      questionNumber: 10,
      topic: 'Planetary Aspects (Drishti)',
      question: 'Which special aspects (Drishtis) does Mangala (Mars) cast in addition to its 7th house aspect?',
      options: [
        '3rd and 10th houses from itself',
        '5th and 9th houses from itself',
        '4th and 8th houses from itself',
        '2nd and 12th houses from itself',
      ],
      correctOptionIndex: 2,
      explanation: 'Mars possesses special full aspects on the 4th and 8th houses from its placement, in addition to the standard universal 7th aspect.',
    },
    {
      id: 'q11',
      questionNumber: 11,
      topic: 'Planetary Aspects (Drishti)',
      question: 'Which planet casts full divine aspects on the 5th and 9th houses from its placement?',
      options: [
        'Saturn (Shani)',
        'Jupiter (Guru)',
        'Venus (Shukra)',
        'Mercury (Budha)',
      ],
      correctOptionIndex: 1,
      explanation: 'Guru (Jupiter) casts full trinal aspects on the 5th and 9th houses from where it sits, imparting protection and auspicious grace.',
    },
    {
      id: 'q12',
      questionNumber: 12,
      topic: 'Planets & Psychology',
      question: 'Which planet is regarded as the Manokaraka (significator of the human mind and emotions)?',
      options: [
        'Surya (Sun)',
        'Chandra (Moon)',
        'Budha (Mercury)',
        'Guru (Jupiter)',
      ],
      correctOptionIndex: 1,
      explanation: 'The Moon (Chandra) is the Karaka for the mind, psychological perceptions, emotional responses, and maternal bond.',
    },
    {
      id: 'q13',
      questionNumber: 13,
      topic: 'The Ascendant (Lagna)',
      question: 'Approximately how often does the Ascendant (Lagna) sign change on the eastern horizon?',
      options: [
        'Every 2 hours',
        'Every 24 hours',
        'Every 2.5 days',
        'Every 30 days',
      ],
      correctOptionIndex: 0,
      explanation: 'Because the Earth rotates 360 degrees in approximately 24 hours, each of the 12 zodiac signs rises on the horizon for roughly 2 hours.',
    },
    {
      id: 'q14',
      questionNumber: 14,
      topic: 'Planetary Dignity',
      question: 'In which sign is Guru (Jupiter) debilitated (Neecha)?',
      options: [
        'Cancer',
        'Capricorn',
        'Gemini',
        'Virgo',
      ],
      correctOptionIndex: 1,
      explanation: 'Jupiter is exalted in Cancer and debilitated in the opposite sign, Capricorn (Makara) at 5 degrees.',
    },
    {
      id: 'q15',
      questionNumber: 15,
      topic: 'Houses (Bhavas)',
      question: 'Which house is primarily inspected to analyze a native\'s career, public status, and professional legacy?',
      options: [
        '6th House',
        '7th House',
        '10th House (Karma Bhava)',
        '11th House',
      ],
      correctOptionIndex: 2,
      explanation: 'The 10th House (Karma Bhava) represents career, profession, public standing, authority, and accomplishments in the outer world.',
    },
    {
      id: 'q16',
      questionNumber: 16,
      topic: 'Houses (Bhavas)',
      question: 'The Trikona (Trine) houses (1, 5, and 9) belong to which Purushartha (aim of life)?',
      options: [
        'Dharma (Righteousness, Purpose & Soul Duty)',
        'Artha (Wealth and Material Security)',
        'Kama (Desire and Relationships)',
        'Moksha (Liberation and Detachment)',
      ],
      correctOptionIndex: 0,
      explanation: 'Houses 1, 5, and 9 are the Dharma Trikonas, representing spiritual merit, auspicious fortune, higher wisdom, and sacred purpose.',
    },
    {
      id: 'q17',
      questionNumber: 17,
      topic: 'Rahu & Ketu',
      question: 'Astronomically and energetically, what are Rahu and Ketu in Vedic astrology?',
      options: [
        'Physical moons orbiting Saturn',
        'The mathematical intersection points (Nodes) of the Moon’s orbital path and the Sun’s ecliptic',
        'Asteroids between Mars and Jupiter',
        'Stars in the Pleiades constellation',
      ],
      correctOptionIndex: 1,
      explanation: 'Rahu and Ketu are the North and South Lunar Nodes — invisible intersection points where the Moon’s orbital plane crosses the ecliptic, where eclipses occur.',
    },
    {
      id: 'q18',
      questionNumber: 18,
      topic: 'Planetary Dignity',
      question: 'What occurs when a planet is "Combust" (Asta)?',
      options: [
        'It is located in an enemy sign',
        'It is retrograding backwards',
        'It is within close degrees of the Sun, causing its physical ray visibility to be obscured',
        'It is placed in the 8th house',
      ],
      correctOptionIndex: 2,
      explanation: 'Combustion (Asta) occurs when a planet comes within close degree proximity to the Sun, causing it to be overpowered by the Sun’s intense solar energy.',
    },
    {
      id: 'q19',
      questionNumber: 19,
      topic: 'Ethics & Consultation',
      question: 'What is the primary ethical responsibility of a Vedic astrologer during a chart consultation?',
      options: [
        'To instill absolute fear of upcoming malefic periods to mandate expensive rituals',
        'To demonstrate intellectual superiority by predicting exact disaster dates',
        'To illuminate karmic patterns compassionately, restore agency, and provide uplifting guidance',
        'To promise that free will is completely nonexistent',
      ],
      correctOptionIndex: 2,
      explanation: 'As taught by Acharya Dr. Hemant at Viar.in and Aapka Astro, Jyotish is a light to illuminate the soul’s path, empower conscious decisions, and provide uplifting, compassionate clarity.',
    },
    {
      id: 'q20',
      questionNumber: 20,
      topic: 'Synthesis',
      question: 'What is the correct first step when opening any birth chart according to the 5-Step Synthesis protocol?',
      options: [
        'Immediately look at the 8th house for accidents',
        'Identify the Lagna (Ascendant), its sign, degree, and locate the placement and dignity of the Lagna Lord (Lagnesha)',
        'Check Saturn\'s transit over the Moon',
        'Check the Nakshatra of Mars',
      ],
      correctOptionIndex: 1,
      explanation: 'The foundation of all chart interpretation starts with the Lagna (Ascendant) and the Lagna Lord (Lagnesha), establishing the strength, orientation, and vitality of the physical native.',
    },
  ],
};

export const DEMO_USERS: User[] = [
  {
    id: 'user-student-demo',
    name: 'Aarav Sharma',
    email: 'student@example.com',
    role: 'STUDENT',
    timezone: 'Asia/Kolkata',
    avatarUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?q=80&w=200&auto=format&fit=crop',
    enrolledCohortIds: ['cohort-wia-batch-1'],
  },
  {
    id: 'user-admin-demo',
    name: 'Acharya Dr. Hemant Vashishta',
    email: 'admin@viar.in',
    role: 'ADMIN',
    timezone: 'Asia/Kolkata',
    avatarUrl: 'https://images.unsplash.com/photo-1544717305-2782549b5136?q=80&w=200&auto=format&fit=crop',
    enrolledCohortIds: ['cohort-wia-batch-1', 'cohort-dashas-batch-1'],
  },
];

export const DEMO_CERTIFICATES: Certificate[] = [
  {
    id: 'cert-wia-9842',
    verificationCode: 'VIAR-2026-WIA-9842',
    studentId: 'user-student-demo',
    studentName: 'Aarav Sharma',
    studentEmail: 'student@example.com',
    courseId: 'course-what-is-astrology',
    courseTitle: 'What is Astrology: Foundational Immersion',
    cohortBatchName: 'Autumn 2026 Batch (Cohort 01)',
    issueDate: 'October 15, 2026',
    scorePercentage: 90,
    grade: 'Distinction',
    instructorName: 'Acharya Dr. Hemant Vashishta',
    instructorTitle: 'Founder, Aapka Astro & Master Astrologer',
    verificationUrl: 'https://viar.in/verify/VIAR-2026-WIA-9842',
  },
];

export const DEMO_ENROLLMENTS: Enrollment[] = [
  {
    id: 'enr-101',
    studentId: 'user-student-demo',
    studentName: 'Aarav Sharma',
    studentEmail: 'student@example.com',
    courseId: 'course-what-is-astrology',
    cohortId: 'cohort-wia-batch-1',
    enrolledAt: '2026-09-20T10:30:00.000Z',
    paymentStatus: 'PAID',
    paymentAmount: 14999,
    currency: 'INR',
    paymentMethod: 'UPI / Razorpay',
    paymentId: 'pay_Nz9KqP03948Viar',
  },
  {
    id: 'enr-102',
    studentId: 'user-priya-patel',
    studentName: 'Priya Patel',
    studentEmail: 'priya.p@gmail.com',
    courseId: 'course-what-is-astrology',
    cohortId: 'cohort-wia-batch-1',
    enrolledAt: '2026-09-20T14:15:00.000Z',
    paymentStatus: 'PAID',
    paymentAmount: 199,
    currency: 'USD',
    paymentMethod: 'International Card / Stripe',
    paymentId: 'ch_3M48KqP03948Stripe',
  },
  {
    id: 'enr-103',
    studentId: 'user-michael-chang',
    studentName: 'Michael Chang',
    studentEmail: 'm.chang@sydney.edu.au',
    courseId: 'course-what-is-astrology',
    cohortId: 'cohort-wia-batch-1',
    enrolledAt: '2026-09-21T02:40:00.000Z',
    paymentStatus: 'PAID',
    paymentAmount: 199,
    currency: 'USD',
    paymentMethod: 'Stripe Checkout',
    paymentId: 'ch_90ViarStripeGlobal',
  },
];
